registerCarModels([
    {
        "id": "id-7-pro-77-2023",
        "brandId": "volkswagen",
        "name": "ID.7",
        "trim": "Pro",
        "range": 560,
        "battery": 77,
        "weightKg": 2110,
        "dragCoefficient": 0.23,
        "img": "img/cars/volkswagen/Volkswagen_ID.7_PRO.png",
        "power": "210 kW (286 HP)",
        "acceleration": "6.7 s (0-100 km/h)",
        "topSpeed": "180 km/h",
        "batteryType": "Li-ion",
        "driveType": "RWD",
        "charging": "175 kW DC",
        "seats": "5",
        "year": "2023+"
    },
    {
        "id": "id-7-pro-s-86-2023",
        "brandId": "volkswagen",
        "name": "ID.7",
        "trim": "Pro S",
        "range": 620,
        "battery": 86,
        "weightKg": 2180,
        "dragCoefficient": 0.23,
        "img": "img/cars/volkswagen/Volkswagen_ID.7_PRO.png",
        "power": "210 kW (286 HP)",
        "acceleration": "6.5 s (0-100 km/h)",
        "topSpeed": "180 km/h",
        "batteryType": "Li-ion",
        "driveType": "RWD",
        "charging": "200 kW DC",
        "seats": "5",
        "year": "2023+"
    },
    {
        "id": "id-7-tourer-gtx-86-2023",
        "brandId": "volkswagen",
        "name": "ID.7",
        "trim": "Tourer GTX",
        "range": 590,
        "battery": 86,
        "weightKg": 2295,
        "dragCoefficient": 0.24,
        "img": "img/cars/volkswagen/Volkswagen_ID.7.png",
        "power": "250 kW (340 HP)",
        "acceleration": "5.5 s (0-100 km/h)",
        "topSpeed": "180 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "200 kW DC",
        "seats": "5",
        "year": "2023+"
    },
    {
        "id": "id-7-tourer-pro-77-2023",
        "brandId": "volkswagen",
        "name": "ID.7",
        "trim": "Tourer Pro",
        "range": 545,
        "battery": 77,
        "weightKg": 2205,
        "dragCoefficient": 0.24,
        "img": "img/cars/volkswagen/Volkswagen_ID.7.png",
        "power": "210 kW (286 HP)",
        "acceleration": "6.9 s (0-100 km/h)",
        "topSpeed": "180 km/h",
        "batteryType": "Li-ion",
        "driveType": "RWD",
        "charging": "175 kW DC",
        "seats": "5",
        "year": "2023+"
    },
    {
        "id": "id-7-tourer-pro-s-86-2023",
        "brandId": "volkswagen",
        "name": "ID.7",
        "trim": "Tourer Pro S",
        "range": 605,
        "battery": 86,
        "weightKg": 2250,
        "dragCoefficient": 0.24,
        "img": "img/cars/volkswagen/Volkswagen_ID.7.png",
        "power": "210 kW (286 HP)",
        "acceleration": "6.8 s (0-100 km/h)",
        "topSpeed": "180 km/h",
        "batteryType": "Li-ion",
        "driveType": "RWD",
        "charging": "200 kW DC",
        "seats": "5",
        "year": "2023+"
    }
]);
