registerCarModels([
    {
        "id": "q4-e-tron-35-2020",
        "brandId": "audi",
        "name": "Q4 e-tron",
        "trim": "35",
        "range": 350,
        "battery": 52,
        "weightKg": 1965,
        "dragCoefficient": 0.28,
        "img": "img/cars/audi/Audi_q4_e-tron.png",
        "power": "125 kW (170 HP)",
        "acceleration": "9.0 s (0-100 km/h)",
        "topSpeed": "160 km/h",
        "batteryType": "Li-ion",
        "driveType": "RWD",
        "charging": "100 kW DC",
        "seats": "5",
        "year": "2020+"
    },
    {
        "id": "q4-e-tron-35-2020",
        "brandId": "audi",
        "name": "Q4 e-tron",
        "trim": "35",
        "range": 350,
        "battery": 52,
        "weightKg": 1965,
        "dragCoefficient": 0.28,
        "img": "img/cars/audi/Audi_q4_e-tron.png",
        "power": "125 kW (170 HP)",
        "acceleration": "9.0 s (0-100 km/h)",
        "topSpeed": "160 km/h",
        "batteryType": "Li-ion",
        "driveType": "RWD",
        "charging": "100 kW DC",
        "seats": "5",
        "year": "2020+"
    },
    {
        "id": "q4-e-tron-40-2020",
        "brandId": "audi",
        "name": "Q4 e-tron",
        "trim": "40",
        "range": 520,
        "battery": 77,
        "weightKg": 2050,
        "dragCoefficient": 0.28,
        "img": "img/cars/audi/Audi_q4_e-tron.png",
        "power": "150 kW (204 HP)",
        "acceleration": "8.5 s (0-100 km/h)",
        "topSpeed": "160 km/h",
        "batteryType": "Li-ion",
        "driveType": "RWD",
        "charging": "125 kW DC",
        "seats": "5",
        "year": "2020+"
    },
    {
        "id": "q4-e-tron-40-sportback-2020",
        "brandId": "audi",
        "name": "Q4 e-tron",
        "trim": "40 Sportback",
        "range": 535,
        "battery": 77,
        "weightKg": 2060,
        "dragCoefficient": 0.27,
        "img": "img/cars/audi/Audi_q4_e-tron.png",
        "power": "150 kW (204 HP)",
        "acceleration": "8.5 s (0-100 km/h)",
        "topSpeed": "160 km/h",
        "batteryType": "Li-ion",
        "driveType": "RWD",
        "charging": "125 kW DC",
        "seats": "5",
        "year": "2020+"
    },
    {
        "id": "q4-e-tron-45-quattro-2020",
        "brandId": "audi",
        "name": "Q4 e-tron",
        "trim": "45 quattro",
        "range": 495,
        "battery": 77,
        "weightKg": 2140,
        "dragCoefficient": 0.28,
        "img": "img/cars/audi/Audi_q4_e-tron.png",
        "power": "195 kW (265 HP)",
        "acceleration": "6.9 s (0-100 km/h)",
        "topSpeed": "180 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "135 kW DC",
        "seats": "5",
        "year": "2020+"
    },
    {
        "id": "q4-e-tron-45-quattro-sportback-2020",
        "brandId": "audi",
        "name": "Q4 e-tron",
        "trim": "45 quattro Sportback",
        "range": 505,
        "battery": 77,
        "weightKg": 2150,
        "dragCoefficient": 0.27,
        "img": "img/cars/audi/Audi_q4_e-tron.png",
        "power": "195 kW (265 HP)",
        "acceleration": "6.9 s (0-100 km/h)",
        "topSpeed": "180 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "135 kW DC",
        "seats": "5",
        "year": "2020+"
    },
    {
        "id": "q4-e-tron-45-sportback-2020",
        "brandId": "audi",
        "name": "Q4 e-tron",
        "trim": "45 Sportback",
        "range": 540,
        "battery": 77,
        "weightKg": 2085,
        "dragCoefficient": 0.27,
        "img": "img/cars/audi/Audi_q4_e-tron.png",
        "power": "210 kW (286 HP)",
        "acceleration": "6.7 s (0-100 km/h)",
        "topSpeed": "180 km/h",
        "batteryType": "Li-ion",
        "driveType": "RWD",
        "charging": "135 kW DC",
        "seats": "5",
        "year": "2020+"
    },
    {
        "id": "q4-e-tron-50-quattro-2020",
        "brandId": "audi",
        "name": "Q4 e-tron",
        "trim": "50 quattro",
        "range": 490,
        "battery": 77,
        "weightKg": 2190,
        "dragCoefficient": 0.28,
        "img": "img/cars/audi/Audi_q4_e-tron.png",
        "power": "220 kW (299 HP)",
        "acceleration": "6.2 s (0-100 km/h)",
        "topSpeed": "180 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "135 kW DC",
        "seats": "5",
        "year": "2020+"
    },
    {
        "id": "q4-e-tron-50-quattro-sportback-2020",
        "brandId": "audi",
        "name": "Q4 e-tron",
        "trim": "50 quattro Sportback",
        "range": 505,
        "battery": 77,
        "weightKg": 2200,
        "dragCoefficient": 0.27,
        "img": "img/cars/audi/Audi_q4_e-tron.png",
        "power": "220 kW (299 HP)",
        "acceleration": "6.2 s (0-100 km/h)",
        "topSpeed": "180 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "135 kW DC",
        "seats": "5",
        "year": "2020+"
    },
    {
        "id": "q4-e-tron-55-quattro-2020",
        "brandId": "audi",
        "name": "Q4 e-tron",
        "trim": "55 quattro",
        "range": 470,
        "battery": 77,
        "weightKg": 2220,
        "dragCoefficient": 0.28,
        "img": "img/cars/audi/Audi_q4_e-tron.png",
        "power": "250 kW (340 HP)",
        "acceleration": "5.4 s (0-100 km/h)",
        "topSpeed": "180 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "135 kW DC",
        "seats": "5",
        "year": "2020+"
    },
    {
        "id": "q4-e-tron-55-quattro-sportback-2020",
        "brandId": "audi",
        "name": "Q4 e-tron",
        "trim": "55 quattro Sportback",
        "range": 485,
        "battery": 77,
        "weightKg": 2230,
        "dragCoefficient": 0.27,
        "img": "img/cars/audi/Audi_q4_e-tron.png",
        "power": "250 kW (340 HP)",
        "acceleration": "5.4 s (0-100 km/h)",
        "topSpeed": "180 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "135 kW DC",
        "seats": "5",
        "year": "2020+"
    }
]);
