registerCarModels([
    {
        "id": "model-s-100d-2017",
        "brandId": "tesla",
        "name": "Model S",
        "trim": "100D",
        "range": 507,
        "battery": 98,
        "weightKg": 2240,
        "dragCoefficient": 0.21,
        "img": "img/cars/tesla/Tesla_Model_S2.png",
        "power": "310 kW (422 HP)",
        "acceleration": "4.3 s (0-100 km/h)",
        "topSpeed": "250 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "120 kW DC",
        "seats": "5",
        "year": "2012-2018"
    },
    {
        "id": "model-s-60-2016",
        "brandId": "tesla",
        "name": "Model S",
        "trim": "60",
        "range": 335,
        "battery": 58.5,
        "weightKg": 2100,
        "dragCoefficient": 0.24,
        "img": "img/cars/tesla/Tesla_Model_S.png",
        "power": "235 kW (320 HP)",
        "acceleration": "5.8 s (0-100 km/h)",
        "topSpeed": "210 km/h",
        "batteryType": "Li-ion",
        "driveType": "RWD",
        "charging": "120 kW DC",
        "seats": "5",
        "year": "2012-2018"
    },
    {
        "id": "model-s-60-75-2016",
        "brandId": "tesla",
        "name": "Model S",
        "trim": "60 (75)",
        "range": 400,
        "battery": 62.4,
        "weightKg": 2110,
        "dragCoefficient": 0.24,
        "img": "img/cars/tesla/Tesla_Model_S2.png",
        "power": "235 kW (320 HP)",
        "acceleration": "5.8 s (0-100 km/h)",
        "topSpeed": "210 km/h",
        "batteryType": "Li-ion",
        "driveType": "RWD",
        "charging": "120 kW DC",
        "seats": "5",
        "year": "2012-2018"
    },
    {
        "id": "model-s-60d-2016",
        "brandId": "tesla",
        "name": "Model S",
        "trim": "60D",
        "range": 350,
        "battery": 58.5,
        "weightKg": 2180,
        "dragCoefficient": 0.24,
        "img": "img/cars/tesla/Tesla_Model_S.png",
        "power": "285 kW (387 HP)",
        "acceleration": "5.4 s (0-100 km/h)",
        "topSpeed": "225 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "120 kW DC",
        "seats": "5",
        "year": "2012-2018"
    },
    {
        "id": "model-s-60d-75-2016",
        "brandId": "tesla",
        "name": "Model S",
        "trim": "60D (75)",
        "range": 417,
        "battery": 62.4,
        "weightKg": 2190,
        "dragCoefficient": 0.24,
        "img": "img/cars/tesla/Tesla_Model_S.png",
        "power": "285 kW (387 HP)",
        "acceleration": "5.4 s (0-100 km/h)",
        "topSpeed": "225 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "120 kW DC",
        "seats": "5",
        "year": "2012-2018"
    },
    {
        "id": "model-s-70-2015",
        "brandId": "tesla",
        "name": "Model S",
        "trim": "70",
        "range": 386,
        "battery": 68.8,
        "weightKg": 2115,
        "dragCoefficient": 0.24,
        "img": "img/cars/tesla/Tesla_Model_S.png",
        "power": "235 kW (320 HP)",
        "acceleration": "5.8 s (0-100 km/h)",
        "topSpeed": "225 km/h",
        "batteryType": "Li-ion",
        "driveType": "RWD",
        "charging": "120 kW DC",
        "seats": "5",
        "year": "2012-2018"
    },
    {
        "id": "model-s-70d-2015",
        "brandId": "tesla",
        "name": "Model S",
        "trim": "70D",
        "range": 400,
        "battery": 68.8,
        "weightKg": 2195,
        "dragCoefficient": 0.24,
        "img": "img/cars/tesla/Tesla_Model_S.png",
        "power": "285 kW (387 HP)",
        "acceleration": "5.4 s (0-100 km/h)",
        "topSpeed": "225 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "120 kW DC",
        "seats": "5",
        "year": "2012-2018"
    },
    {
        "id": "model-s-75-2016",
        "brandId": "tesla",
        "name": "Model S",
        "trim": "75",
        "range": 430,
        "battery": 72.6,
        "weightKg": 2130,
        "dragCoefficient": 0.24,
        "img": "img/cars/tesla/Tesla_Model_S.png",
        "power": "235 kW (320 HP)",
        "acceleration": "5.7 s (0-100 km/h)",
        "topSpeed": "225 km/h",
        "batteryType": "Li-ion",
        "driveType": "RWD",
        "charging": "120 kW DC",
        "seats": "5",
        "year": "2012-2018"
    },
    {
        "id": "model-s-75-85kwh-2016",
        "brandId": "tesla",
        "name": "Model S",
        "trim": "75 (85 kWh)",
        "range": 438,
        "battery": 72.6,
        "weightKg": 2140,
        "dragCoefficient": 0.24,
        "img": "img/cars/tesla/Tesla_Model_S.png",
        "power": "235 kW (320 HP)",
        "acceleration": "5.7 s (0-100 km/h)",
        "topSpeed": "225 km/h",
        "batteryType": "Li-ion",
        "driveType": "RWD",
        "charging": "120 kW DC",
        "seats": "5",
        "year": "2012-2018"
    },
    {
        "id": "model-s-75d-2016",
        "brandId": "tesla",
        "name": "Model S",
        "trim": "75D",
        "range": 442,
        "battery": 72.6,
        "weightKg": 2210,
        "dragCoefficient": 0.24,
        "img": "img/cars/tesla/Tesla_Model_S.png",
        "power": "285 kW (387 HP)",
        "acceleration": "5.4 s (0-100 km/h)",
        "topSpeed": "225 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "120 kW DC",
        "seats": "5",
        "year": "2012-2018"
    },
    {
        "id": "model-s-75d-85kwh-2016",
        "brandId": "tesla",
        "name": "Model S",
        "trim": "75D (85 kWh)",
        "range": 450,
        "battery": 72.6,
        "weightKg": 2220,
        "dragCoefficient": 0.24,
        "img": "img/cars/tesla/Tesla_Model_S.png",
        "power": "285 kW (387 HP)",
        "acceleration": "5.4 s (0-100 km/h)",
        "topSpeed": "225 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "120 kW DC",
        "seats": "5",
        "year": "2012-2018"
    },
    {
        "id": "model-s-85-2014",
        "brandId": "tesla",
        "name": "Model S",
        "trim": "85",
        "range": 502,
        "battery": 77.5,
        "weightKg": 2145,
        "dragCoefficient": 0.24,
        "img": "img/cars/tesla/Tesla_Model_S.png",
        "power": "270 kW (367 HP)",
        "acceleration": "5.6 s (0-100 km/h)",
        "topSpeed": "225 km/h",
        "batteryType": "Li-ion",
        "driveType": "RWD",
        "charging": "120 kW DC",
        "seats": "5",
        "year": "2012-2018"
    },
    {
        "id": "model-s-85d-2015",
        "brandId": "tesla",
        "name": "Model S",
        "trim": "85D",
        "range": 530,
        "battery": 77.5,
        "weightKg": 2230,
        "dragCoefficient": 0.24,
        "img": "img/cars/tesla/Tesla_Model_S.png",
        "power": "310 kW (422 HP)",
        "acceleration": "4.6 s (0-100 km/h)",
        "topSpeed": "250 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "120 kW DC",
        "seats": "5",
        "year": "2012-2018"
    },
    {
        "id": "model-s-90d-2016",
        "brandId": "tesla",
        "name": "Model S",
        "trim": "90D",
        "range": 557,
        "battery": 82,
        "weightKg": 2240,
        "dragCoefficient": 0.24,
        "img": "img/cars/tesla/Tesla_Model_S.png",
        "power": "310 kW (422 HP)",
        "acceleration": "4.4 s (0-100 km/h)",
        "topSpeed": "250 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "120 kW DC",
        "seats": "5",
        "year": "2012-2018"
    },
    {
        "id": "model-s-p100d-2017",
        "brandId": "tesla",
        "name": "Model S",
        "trim": "P100D",
        "range": 613,
        "battery": 98,
        "weightKg": 2265,
        "dragCoefficient": 0.24,
        "img": "img/cars/tesla/Tesla_Model_S.png",
        "power": "568 kW (773 HP)",
        "acceleration": "2.7 s (0-100 km/h)",
        "topSpeed": "250 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "120 kW DC",
        "seats": "5",
        "year": "2012-2018"
    },
    {
        "id": "model-s-p85-2014",
        "brandId": "tesla",
        "name": "Model S",
        "trim": "P85",
        "range": 450,
        "battery": 77.5,
        "weightKg": 2160,
        "dragCoefficient": 0.24,
        "img": "img/cars/tesla/Tesla_Model_S.png",
        "power": "310 kW (422 HP)",
        "acceleration": "4.4 s (0-100 km/h)",
        "topSpeed": "250 km/h",
        "batteryType": "Li-ion",
        "driveType": "RWD",
        "charging": "120 kW DC",
        "seats": "5",
        "year": "2012-2018"
    },
    {
        "id": "model-s-p85d-2015",
        "brandId": "tesla",
        "name": "Model S",
        "trim": "P85D",
        "range": 470,
        "battery": 77.5,
        "weightKg": 2255,
        "dragCoefficient": 0.24,
        "img": "img/cars/tesla/Tesla_Model_S.png",
        "power": "515 kW (700 HP)",
        "acceleration": "3.2 s (0-100 km/h)",
        "topSpeed": "250 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "120 kW DC",
        "seats": "5",
        "year": "2012-2018"
    },
    {
        "id": "model-s-p90d-2016",
        "brandId": "tesla",
        "name": "Model S",
        "trim": "P90D",
        "range": 509,
        "battery": 82,
        "weightKg": 2260,
        "dragCoefficient": 0.24,
        "img": "img/cars/tesla/Tesla_Model_S.png",
        "power": "568 kW (773 HP)",
        "acceleration": "2.8 s (0-100 km/h)",
        "topSpeed": "250 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "120 kW DC",
        "seats": "5",
        "year": "2012-2018"
    },
    {
        "id": "model-s-early-2019-long-range-100d",
        "brandId": "tesla",
        "name": "Model S",
        "trim": "Early 2019 Long Range 100D",
        "range": 595,
        "battery": 98,
        "weightKg": 2245,
        "dragCoefficient": 0.23,
        "img": "img/cars/tesla/Tesla_Model_S_facelift.png",
        "power": "340 kW (462 HP)",
        "acceleration": "4.1 s (0-100 km/h)",
        "topSpeed": "250 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "150 kW DC",
        "seats": "5",
        "year": "2019"
    },
    {
        "id": "model-s-early-2019-performance-p100d",
        "brandId": "tesla",
        "name": "Model S",
        "trim": "Early 2019 Performance P100D",
        "range": 560,
        "battery": 98,
        "weightKg": 2265,
        "dragCoefficient": 0.23,
        "img": "img/cars/tesla/Tesla_Model_S_facelift.png",
        "power": "568 kW (773 HP)",
        "acceleration": "2.7 s (0-100 km/h)",
        "topSpeed": "261 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "150 kW DC",
        "seats": "5",
        "year": "2019"
    },
    {
        "id": "model-s-early-2019-standard-range",
        "brandId": "tesla",
        "name": "Model S",
        "trim": "Early 2019 Standard Range",
        "range": 460,
        "battery": 79,
        "weightKg": 2150,
        "dragCoefficient": 0.23,
        "img": "img/cars/tesla/Tesla_Model_S_facelift.png",
        "power": "225 kW (306 HP)",
        "acceleration": "5.6 s (0-100 km/h)",
        "topSpeed": "230 km/h",
        "batteryType": "Li-ion",
        "driveType": "RWD",
        "charging": "150 kW DC",
        "seats": "5",
        "year": "2019"
    },
    {
        "id": "model-s-raven-long-range-2019",
        "brandId": "tesla",
        "name": "Model S",
        "trim": "Range Upgrade (Raven) Long Range",
        "range": 610,
        "battery": 98,
        "weightKg": 2230,
        "dragCoefficient": 0.23,
        "img": "img/cars/tesla/Tesla_Model_S_facelift.png",
        "power": "340 kW (462 HP)",
        "acceleration": "3.8 s (0-100 km/h)",
        "topSpeed": "250 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "150 kW DC",
        "seats": "5",
        "year": "2019"
    },
    {
        "id": "model-s-raven-performance-2019",
        "brandId": "tesla",
        "name": "Model S",
        "trim": "Range Upgrade (Raven) Performance",
        "range": 590,
        "battery": 98,
        "weightKg": 2255,
        "dragCoefficient": 0.23,
        "img": "img/cars/tesla/Tesla_Model_S_facelift.png",
        "power": "580 kW (789 HP)",
        "acceleration": "2.6 s (0-100 km/h)",
        "topSpeed": "261 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "150 kW DC",
        "seats": "5",
        "year": "2019"
    },
    {
        "id": "model-s-raven-standard-range-2019",
        "brandId": "tesla",
        "name": "Model S",
        "trim": "Range Upgrade (Raven) Standard Range",
        "range": 495,
        "battery": 79,
        "weightKg": 2210,
        "dragCoefficient": 0.23,
        "img": "img/cars/tesla/Tesla_Model_S_facelift.png",
        "power": "310 kW (422 HP)",
        "acceleration": "4.4 s (0-100 km/h)",
        "topSpeed": "250 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "150 kW DC",
        "seats": "5",
        "year": "2019"
    },
    {
        "id": "model-s-long-range-plus-2020",
        "brandId": "tesla",
        "name": "Model S",
        "trim": "Long Range Plus",
        "range": 647,
        "battery": 98,
        "weightKg": 2220,
        "dragCoefficient": 0.21,
        "img": "img/cars/tesla/Tesla_Model_S_facelift.png",
        "power": "500 kW (670 HP)",
        "acceleration": "3.8 s (0-100 km/h)",
        "topSpeed": "250 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "200 kW DC",
        "seats": "5",
        "year": "2020"
    },
    {
        "id": "model-s-performance-2020",
        "brandId": "tesla",
        "name": "Model S",
        "trim": "Performance",
        "range": 610,
        "battery": 98,
        "weightKg": 2240,
        "dragCoefficient": 0.21,
        "img": "img/cars/tesla/Tesla_Model_S_facelift.png",
        "power": "580 kW (789 HP)",
        "acceleration": "2.6 s (0-100 km/h)",
        "topSpeed": "261 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "200 kW DC",
        "seats": "5",
        "year": "2020"
    },
    {
        "id": "model-s-facelift-long-range-2021",
        "brandId": "tesla",
        "name": "Model S",
        "trim": "Facelift Long Range",
        "range": 634,
        "battery": 98,
        "weightKg": 2068,
        "dragCoefficient": 0.21,
        "img": "img/cars/tesla/Tesla_Model_S_facelift.png",
        "power": "500 kW (670 HP)",
        "acceleration": "3.2 s (0-100 km/h)",
        "topSpeed": "250 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "250 kW DC",
        "seats": "5",
        "year": "2021"
    },
    {
        "id": "model-s-plaid-2021",
        "brandId": "tesla",
        "name": "Model S",
        "trim": "Plaid",
        "range": 600,
        "battery": 98,
        "weightKg": 2162,
        "dragCoefficient": 0.21,
        "img": "img/cars/tesla/Tesla_Model_S_facelift.png",
        "power": "760 kW (1020 HP)",
        "acceleration": "2.1 s (0-100 km/h)",
        "topSpeed": "322 km/h",
        "batteryType": "Li-ion",
        "driveType": "Tri Motor AWD",
        "charging": "250 kW DC",
        "seats": "5",
        "year": "2021"
    }
]);
