registerCarModels([
    {
        "id": "model-y-long-range-awd-2020",
        "brandId": "tesla",
        "name": "Model Y",
        "trim": "Long Range AWD",
        "range": 505,
        "battery": 73.5,
        "weightKg": 2010,
        "dragCoefficient": 0.23,
        "img": "img/cars/tesla/Tesla_Model_Y.png",
        "power": "258 kW (351 HP)",
        "acceleration": "5.0 s (0-100 km/h)",
        "topSpeed": "217 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "250 kW DC",
        "seats": "5",
        "year": "2020"
    },
    {
        "id": "model-y-performance-2020",
        "brandId": "tesla",
        "name": "Model Y",
        "trim": "Performance",
        "range": 480,
        "battery": 73.5,
        "weightKg": 2015,
        "dragCoefficient": 0.23,
        "img": "img/cars/tesla/Tesla_Model_Y.png",
        "power": "340 kW (462 HP)",
        "acceleration": "3.7 s (0-100 km/h)",
        "topSpeed": "241 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "250 kW DC",
        "seats": "5",
        "year": "2020"
    },
    {
        "id": "model-y-standard-range-2020",
        "brandId": "tesla",
        "name": "Model Y",
        "trim": "Standard Range",
        "range": 390,
        "battery": 51,
        "weightKg": 1905,
        "dragCoefficient": 0.23,
        "img": "img/cars/tesla/Tesla_Model_Y.png",
        "power": "190 kW (258 HP)",
        "acceleration": "5.9 s (0-100 km/h)",
        "topSpeed": "217 km/h",
        "batteryType": "Li-ion",
        "driveType": "RWD",
        "charging": "170 kW DC",
        "seats": "5",
        "year": "2020"
    },
    {
        "id": "model-y-long-range-2021",
        "brandId": "tesla",
        "name": "Model Y",
        "trim": "Long Range",
        "range": 533,
        "battery": 79,
        "weightKg": 1995,
        "dragCoefficient": 0.23,
        "img": "img/cars/tesla/Tesla_Model_Y.png",
        "power": "258 kW (351 HP)",
        "acceleration": "5.0 s (0-100 km/h)",
        "topSpeed": "217 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "250 kW DC",
        "seats": "5",
        "year": "2021"
    },
    {
        "id": "model-y-performance-2021",
        "brandId": "tesla",
        "name": "Model Y",
        "trim": "Performance",
        "range": 514,
        "battery": 79,
        "weightKg": 2003,
        "dragCoefficient": 0.23,
        "img": "img/cars/tesla/Tesla_Model_Y.png",
        "power": "393 kW (534 HP)",
        "acceleration": "3.7 s (0-100 km/h)",
        "topSpeed": "250 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "250 kW DC",
        "seats": "5",
        "year": "2021"
    },
    {
        "id": "model-y-long-range-2022",
        "brandId": "tesla",
        "name": "Model Y",
        "trim": "Long Range",
        "range": 533,
        "battery": 79,
        "weightKg": 1998,
        "dragCoefficient": 0.23,
        "img": "img/cars/tesla/Tesla_Model_Y.png",
        "power": "258 kW (351 HP)",
        "acceleration": "5.0 s (0-100 km/h)",
        "topSpeed": "217 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "250 kW DC",
        "seats": "5",
        "year": "2022"
    },
    {
        "id": "model-y-long-range-nca-2022",
        "brandId": "tesla",
        "name": "Model Y",
        "trim": "Long Range (NCA battery)",
        "range": 540,
        "battery": 79,
        "weightKg": 2000,
        "dragCoefficient": 0.23,
        "img": "img/cars/tesla/Tesla_Model_Y.png",
        "power": "258 kW (351 HP)",
        "acceleration": "5.0 s (0-100 km/h)",
        "topSpeed": "217 km/h",
        "batteryType": "Li-ion NCA",
        "driveType": "Dual Motor AWD",
        "charging": "250 kW DC",
        "seats": "5",
        "year": "2022"
    },
    {
        "id": "model-y-performance-2022",
        "brandId": "tesla",
        "name": "Model Y",
        "trim": "Performance",
        "range": 514,
        "battery": 79,
        "weightKg": 2005,
        "dragCoefficient": 0.23,
        "img": "img/cars/tesla/Tesla_Model_Y.png",
        "power": "393 kW (534 HP)",
        "acceleration": "3.7 s (0-100 km/h)",
        "topSpeed": "250 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "250 kW DC",
        "seats": "5",
        "year": "2022"
    },
    {
        "id": "model-y-performance-nca-2022",
        "brandId": "tesla",
        "name": "Model Y",
        "trim": "Performance (NCA battery)",
        "range": 520,
        "battery": 79,
        "weightKg": 2007,
        "dragCoefficient": 0.23,
        "img": "img/cars/tesla/Tesla_Model_Y.png",
        "power": "393 kW (534 HP)",
        "acceleration": "3.7 s (0-100 km/h)",
        "topSpeed": "250 km/h",
        "batteryType": "Li-ion NCA",
        "driveType": "Dual Motor AWD",
        "charging": "250 kW DC",
        "seats": "5",
        "year": "2022"
    },
    {
        "id": "model-y-standard-range-60-2022",
        "brandId": "tesla",
        "name": "Model Y",
        "trim": "Standard range (60 kWh)",
        "range": 455,
        "battery": 57.5,
        "weightKg": 1940,
        "dragCoefficient": 0.23,
        "img": "img/cars/tesla/Tesla_Model_Y.png",
        "power": "220 kW (299 HP)",
        "acceleration": "6.0 s (0-100 km/h)",
        "topSpeed": "217 km/h",
        "batteryType": "Li-ion LFP",
        "driveType": "RWD",
        "charging": "170 kW DC",
        "seats": "5",
        "year": "2022"
    },
    {
        "id": "model-y-standard-range-62-2022",
        "brandId": "tesla",
        "name": "Model Y",
        "trim": "Standard range (62 kWh)",
        "range": 470,
        "battery": 57.5,
        "weightKg": 1945,
        "dragCoefficient": 0.23,
        "img": "img/cars/tesla/Tesla_Model_Y.png",
        "power": "220 kW (299 HP)",
        "acceleration": "6.0 s (0-100 km/h)",
        "topSpeed": "217 km/h",
        "batteryType": "Li-ion LFP",
        "driveType": "RWD",
        "charging": "170 kW DC",
        "seats": "5",
        "year": "2022"
    },
    {
        "id": "model-y-standard-range-67-5-2022",
        "brandId": "tesla",
        "name": "Model Y",
        "trim": "Standard range (67.5 kWh)",
        "range": 500,
        "battery": 67,
        "weightKg": 1955,
        "dragCoefficient": 0.23,
        "img": "img/cars/tesla/Tesla_Model_Y.png",
        "power": "235 kW (320 HP)",
        "acceleration": "5.8 s (0-100 km/h)",
        "topSpeed": "217 km/h",
        "batteryType": "Li-ion",
        "driveType": "RWD",
        "charging": "200 kW DC",
        "seats": "5",
        "year": "2022"
    },
    {
        "id": "model-y-long-range-2023",
        "brandId": "tesla",
        "name": "Model Y",
        "trim": "Long Range",
        "range": 533,
        "battery": 79,
        "weightKg": 1998,
        "dragCoefficient": 0.23,
        "img": "img/cars/tesla/Tesla_Model_Y.png",
        "power": "258 kW (351 HP)",
        "acceleration": "5.0 s (0-100 km/h)",
        "topSpeed": "217 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "250 kW DC",
        "seats": "5",
        "year": "2023-2024"
    },
    {
        "id": "model-y-performance-2023",
        "brandId": "tesla",
        "name": "Model Y",
        "trim": "Performance",
        "range": 514,
        "battery": 79,
        "weightKg": 2005,
        "dragCoefficient": 0.23,
        "img": "img/cars/tesla/Tesla_Model_Y.png",
        "power": "393 kW (534 HP)",
        "acceleration": "3.7 s (0-100 km/h)",
        "topSpeed": "250 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "250 kW DC",
        "seats": "5",
        "year": "2023-2024"
    },
    {
        "id": "model-y-standard-range-2023",
        "brandId": "tesla",
        "name": "Model Y",
        "trim": "Standard range",
        "range": 455,
        "battery": 57.5,
        "weightKg": 1940,
        "dragCoefficient": 0.23,
        "img": "img/cars/tesla/Tesla_Model_Y.png",
        "power": "220 kW (299 HP)",
        "acceleration": "6.0 s (0-100 km/h)",
        "topSpeed": "217 km/h",
        "batteryType": "Li-ion LFP",
        "driveType": "RWD",
        "charging": "170 kW DC",
        "seats": "5",
        "year": "2023-2024"
    },
    {
        "id": "model-y-long-range-awd-2025",
        "brandId": "tesla",
        "name": "Model Y",
        "trim": "Long Range AWD",
        "range": 570,
        "battery": 75,
        "weightKg": 1995,
        "dragCoefficient": 0.22,
        "img": "img/cars/tesla/Tesla_Model_Y_rest.png",
        "power": "378 kW (514 HP)",
        "acceleration": "4.8 s (0-100 km/h)",
        "topSpeed": "217 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "250 kW DC",
        "seats": "5",
        "year": "2025",
        "isEstimate": true
    },
    {
        "id": "model-y-long-range-rwd-2025",
        "brandId": "tesla",
        "name": "Model Y",
        "trim": "Long Range RWD",
        "range": 600,
        "battery": 75,
        "weightKg": 1945,
        "dragCoefficient": 0.22,
        "img": "img/cars/tesla/Tesla_Model_Y_rest.png",
        "power": "230 kW (313 HP)",
        "acceleration": "5.5 s (0-100 km/h)",
        "topSpeed": "217 km/h",
        "batteryType": "Li-ion",
        "driveType": "RWD",
        "charging": "250 kW DC",
        "seats": "5",
        "year": "2025",
        "isEstimate": true
    },
    {
        "id": "model-y-standard-range-rwd-2025",
        "brandId": "tesla",
        "name": "Model Y",
        "trim": "Standard Range RWD",
        "range": 485,
        "battery": 60,
        "weightKg": 1925,
        "dragCoefficient": 0.22,
        "img": "img/cars/tesla/Tesla_Model_Y_rest.png",
        "power": "220 kW (299 HP)",
        "acceleration": "6.0 s (0-100 km/h)",
        "topSpeed": "210 km/h",
        "batteryType": "Li-ion LFP",
        "driveType": "RWD",
        "charging": "200 kW DC",
        "seats": "5",
        "year": "2025",
        "isEstimate": true
    },
    {
        "id": "model-y-standard-range-rwd-2025-plus",
        "brandId": "tesla",
        "name": "Model Y",
        "trim": "Standard Range RWD",
        "range": 500,
        "battery": 60,
        "weightKg": 1920,
        "dragCoefficient": 0.22,
        "img": "img/cars/tesla/Tesla_Model_Y_rest.png",
        "power": "220 kW (299 HP)",
        "acceleration": "5.9 s (0-100 km/h)",
        "topSpeed": "210 km/h",
        "batteryType": "Li-ion LFP",
        "driveType": "RWD",
        "charging": "200 kW DC",
        "seats": "5",
        "year": "2025+",
        "isEstimate": true
    },
    {
        "id": "model-y-long-range-awd-2026",
        "brandId": "tesla",
        "name": "Model Y",
        "trim": "Long Range AWD",
        "range": 590,
        "battery": 75,
        "weightKg": 1990,
        "dragCoefficient": 0.22,
        "img": "img/cars/tesla/Tesla_Model_Y_rest.png",
        "power": "378 kW (514 HP)",
        "acceleration": "4.8 s (0-100 km/h)",
        "topSpeed": "220 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "250 kW DC",
        "seats": "5",
        "year": "2026+",
        "isEstimate": true
    },
    {
        "id": "model-y-long-range-rwd-2026",
        "brandId": "tesla",
        "name": "Model Y",
        "trim": "Long Range RWD",
        "range": 620,
        "battery": 75,
        "weightKg": 1940,
        "dragCoefficient": 0.22,
        "img": "img/cars/tesla/Tesla_Model_Y_rest.png",
        "power": "230 kW (313 HP)",
        "acceleration": "5.4 s (0-100 km/h)",
        "topSpeed": "220 km/h",
        "batteryType": "Li-ion",
        "driveType": "RWD",
        "charging": "250 kW DC",
        "seats": "5",
        "year": "2026+",
        "isEstimate": true
    }
]);
