registerCarModels([
    {
        "id": "i3-60ah-2014",
        "brandId": "bmw",
        "name": "i3",
        "trim": "60 Ah",
        "range": 130,
        "battery": 18.8,
        "weightKg": 1195,
        "dragCoefficient": 0.29,
        "img": "img/cars/bmw/BMW_i3.png",
        "power": "125 kW (170 HP)",
        "acceleration": "7.2 s (0-100 km/h)",
        "topSpeed": "150 km/h",
        "batteryType": "Li-ion",
        "driveType": "RWD",
        "charging": "50 kW DC",
        "seats": "4",
        "year": "2014-2016"
    },
    {
        "id": "i3-94ah-2017",
        "brandId": "bmw",
        "name": "i3",
        "trim": "94 Ah",
        "range": 183,
        "battery": 27.2,
        "weightKg": 1245,
        "dragCoefficient": 0.29,
        "img": "img/cars/bmw/BMW_i3.png",
        "power": "125 kW (170 HP)",
        "acceleration": "7.3 s (0-100 km/h)",
        "topSpeed": "150 km/h",
        "batteryType": "Li-ion",
        "driveType": "RWD",
        "charging": "50 kW DC",
        "seats": "4",
        "year": "2017-2018"
    },
    {
        "id": "i3-120ah-2019",
        "brandId": "bmw",
        "name": "i3",
        "trim": "120 Ah",
        "range": 246,
        "battery": 37.9,
        "weightKg": 1270,
        "dragCoefficient": 0.29,
        "img": "img/cars/bmw/BMW_i3.png",
        "power": "125 kW (170 HP)",
        "acceleration": "7.3 s (0-100 km/h)",
        "topSpeed": "150 km/h",
        "batteryType": "Li-ion",
        "driveType": "RWD",
        "charging": "50 kW DC",
        "seats": "4",
        "year": "2019-2021"
    }
]);
