registerCarModels([
    {
        "id": "ix1-edrive20-2024",
        "brandId": "bmw",
        "name": "iX1",
        "trim": "eDrive20",
        "range": 475,
        "battery": 64.7,
        "weightKg": 1940,
        "dragCoefficient": 0.26,
        "img": "img/cars/bmw/BMW_iX1_edrive20.png",
        "power": "150 kW (204 HP)",
        "acceleration": "8.6 s (0-100 km/h)",
        "topSpeed": "170 km/h",
        "batteryType": "Li-ion",
        "driveType": "FWD",
        "charging": "130 kW DC",
        "seats": "5",
        "year": "2024+"
    },
    {
        "id": "ix1-xdrive30-2022",
        "brandId": "bmw",
        "name": "iX1",
        "trim": "xDrive30",
        "range": 440,
        "battery": 64.7,
        "weightKg": 2080,
        "dragCoefficient": 0.26,
        "img": "img/cars/bmw/BMW_iX1_xdrive30.png",
        "power": "230 kW (313 HP)",
        "acceleration": "5.6 s (0-100 km/h)",
        "topSpeed": "180 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "130 kW DC",
        "seats": "5",
        "year": "2022+"
    }
]);
