registerCarModels([
    {
        "id": "q6-e-tron-40-2025",
        "brandId": "audi",
        "name": "Q6 e-tron",
        "trim": "40",
        "range": 645,
        "battery": 100,
        "weightKg": 2180,
        "dragCoefficient": 0.25,
        "img": "img/cars/audi/Audi_q6_e-tron.png",
        "power": "210 kW (286 HP)",
        "acceleration": "7.4 s (0-100 km/h)",
        "topSpeed": "210 km/h",
        "batteryType": "Li-ion",
        "driveType": "RWD",
        "charging": "270 kW DC",
        "seats": "5",
        "year": "2025+"
    },
    {
        "id": "q6-e-tron-55-2025",
        "brandId": "audi",
        "name": "Q6 e-tron",
        "trim": "55",
        "range": 700,
        "battery": 100,
        "weightKg": 2230,
        "dragCoefficient": 0.25,
        "img": "img/cars/audi/Audi_q6_e-tron.png",
        "power": "310 kW (421 HP)",
        "acceleration": "5.3 s (0-100 km/h)",
        "topSpeed": "210 km/h",
        "batteryType": "Li-ion",
        "driveType": "RWD",
        "charging": "270 kW DC",
        "seats": "5",
        "year": "2025+"
    },
    {
        "id": "q6-e-tron-55-quattro-2025",
        "brandId": "audi",
        "name": "Q6 e-tron",
        "trim": "55 quattro",
        "range": 680,
        "battery": 100,
        "weightKg": 2380,
        "dragCoefficient": 0.25,
        "img": "img/cars/audi/Audi_q6_e-tron.png",
        "power": "380 kW (516 HP)",
        "acceleration": "4.8 s (0-100 km/h)",
        "topSpeed": "210 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "270 kW DC",
        "seats": "5",
        "year": "2025+"
    }
]);
