registerCarModels([
    {
        "id": "id-4-pro-awd-77-2024",
        "brandId": "volkswagen",
        "name": "ID.4",
        "trim": "Pro AWD 77 kWh",
        "range": 520,
        "battery": 77,
        "weightKg": 2220,
        "dragCoefficient": 0.28,
        "img": "img/cars/volkswagen/Volkswagen_ID.4.png",
        "power": "220 kW (299 HP)",
        "acceleration": "6.2 s (0-100 km/h)",
        "topSpeed": "180 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "175 kW DC",
        "seats": "5",
        "year": "2024+"
    },
    {
        "id": "id-4-pro-rwd-77-2024",
        "brandId": "volkswagen",
        "name": "ID.4",
        "trim": "Pro RWD 77 kWh",
        "range": 540,
        "battery": 77,
        "weightKg": 2110,
        "dragCoefficient": 0.28,
        "img": "img/cars/volkswagen/Volkswagen_ID.4.png",
        "power": "210 kW (286 HP)",
        "acceleration": "6.7 s (0-100 km/h)",
        "topSpeed": "180 km/h",
        "batteryType": "Li-ion",
        "driveType": "RWD",
        "charging": "175 kW DC",
        "seats": "5",
        "year": "2024+"
    },
    {
        "id": "id-4-pro-gtx-awd-77-2024",
        "brandId": "volkswagen",
        "name": "ID.4",
        "trim": "Pro GTX",
        "range": 500,
        "battery": 77,
        "weightKg": 2240,
        "dragCoefficient": 0.28,
        "img": "img/cars/volkswagen/Volkswagen_ID.4.png",
        "power": "250 kW (340 HP)",
        "acceleration": "5.4 s (0-100 km/h)",
        "topSpeed": "180 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "175 kW DC",
        "seats": "5",
        "year": "2024+"
    },
    {
        "id": "id-4-pure-rwd-52-2024",
        "brandId": "volkswagen",
        "name": "ID.4",
        "trim": "Pure",
        "range": 360,
        "battery": 52,
        "weightKg": 1990,
        "dragCoefficient": 0.29,
        "img": "img/cars/volkswagen/Volkswagen_ID.4.png",
        "power": "125 kW (170 HP)",
        "acceleration": "9.0 s (0-100 km/h)",
        "topSpeed": "160 km/h",
        "batteryType": "Li-ion",
        "driveType": "RWD",
        "charging": "145 kW DC",
        "seats": "5",
        "year": "2024+"
    },
    {
        "id": "id-4-gtx-awd-77-2022",
        "brandId": "volkswagen",
        "name": "ID.4",
        "trim": "GTX AWD 77 kWh",
        "range": 490,
        "battery": 77,
        "weightKg": 2235,
        "dragCoefficient": 0.28,
        "img": "img/cars/volkswagen/Volkswagen_ID.4.png",
        "power": "220 kW (299 HP)",
        "acceleration": "6.2 s (0-100 km/h)",
        "topSpeed": "180 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "135 kW DC",
        "seats": "5",
        "year": "2022-2023"
    },
    {
        "id": "id-4-pro-awd-77-2022",
        "brandId": "volkswagen",
        "name": "ID.4",
        "trim": "Pro AWD 77 kWh",
        "range": 500,
        "battery": 77,
        "weightKg": 2215,
        "dragCoefficient": 0.28,
        "img": "img/cars/volkswagen/Volkswagen_ID.4.png",
        "power": "195 kW (265 HP)",
        "acceleration": "6.9 s (0-100 km/h)",
        "topSpeed": "180 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "135 kW DC",
        "seats": "5",
        "year": "2022-2023"
    },
    {
        "id": "id-4-pro-rwd-77-2022",
        "brandId": "volkswagen",
        "name": "ID.4",
        "trim": "Pro RWD 77 kWh",
        "range": 520,
        "battery": 77,
        "weightKg": 2100,
        "dragCoefficient": 0.28,
        "img": "img/cars/volkswagen/Volkswagen_ID.4.png",
        "power": "150 kW (204 HP)",
        "acceleration": "8.5 s (0-100 km/h)",
        "topSpeed": "160 km/h",
        "batteryType": "Li-ion",
        "driveType": "RWD",
        "charging": "135 kW DC",
        "seats": "5",
        "year": "2022-2023"
    },
    {
        "id": "id-4-standard-rwd-58-2022",
        "brandId": "volkswagen",
        "name": "ID.4",
        "trim": "Standard RWD 58 kWh",
        "range": 360,
        "battery": 58,
        "weightKg": 1965,
        "dragCoefficient": 0.29,
        "img": "img/cars/volkswagen/Volkswagen_ID.4.png",
        "power": "109 kW (148 HP)",
        "acceleration": "10.9 s (0-100 km/h)",
        "topSpeed": "160 km/h",
        "batteryType": "Li-ion",
        "driveType": "RWD",
        "charging": "120 kW DC",
        "seats": "5",
        "year": "2022-2023"
    },
    {
        "id": "id-4-gtx-awd-77-2021",
        "brandId": "volkswagen",
        "name": "ID.4",
        "trim": "GTX AWD 77 kWh",
        "range": 480,
        "battery": 77,
        "weightKg": 2225,
        "dragCoefficient": 0.28,
        "img": "img/cars/volkswagen/Volkswagen_ID.4.png",
        "power": "220 kW (299 HP)",
        "acceleration": "6.2 s (0-100 km/h)",
        "topSpeed": "180 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "125 kW DC",
        "seats": "5",
        "year": "2021"
    },
    {
        "id": "id-4-pro-awd-77-2021",
        "brandId": "volkswagen",
        "name": "ID.4",
        "trim": "Pro AWD 77 kWh",
        "range": 490,
        "battery": 77,
        "weightKg": 2210,
        "dragCoefficient": 0.28,
        "img": "img/cars/volkswagen/Volkswagen_ID.4.png",
        "power": "195 kW (265 HP)",
        "acceleration": "6.9 s (0-100 km/h)",
        "topSpeed": "180 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "125 kW DC",
        "seats": "5",
        "year": "2021"
    },
    {
        "id": "id-4-pro-rwd-77-2021",
        "brandId": "volkswagen",
        "name": "ID.4",
        "trim": "Pro RWD 77 kWh",
        "range": 510,
        "battery": 77,
        "weightKg": 2090,
        "dragCoefficient": 0.28,
        "img": "img/cars/volkswagen/Volkswagen_ID.4.png",
        "power": "150 kW (204 HP)",
        "acceleration": "8.5 s (0-100 km/h)",
        "topSpeed": "160 km/h",
        "batteryType": "Li-ion",
        "driveType": "RWD",
        "charging": "125 kW DC",
        "seats": "5",
        "year": "2021"
    },
    {
        "id": "id-4-pure-rwd-52-2021",
        "brandId": "volkswagen",
        "name": "ID.4",
        "trim": "Pure 52 kWh",
        "range": 340,
        "battery": 52,
        "weightKg": 1980,
        "dragCoefficient": 0.29,
        "img": "img/cars/volkswagen/Volkswagen_ID.4.png",
        "power": "109 kW (148 HP)",
        "acceleration": "10.9 s (0-100 km/h)",
        "topSpeed": "160 km/h",
        "batteryType": "Li-ion",
        "driveType": "RWD",
        "charging": "110 kW DC",
        "seats": "5",
        "year": "2021"
    }
]);
