registerCarModels([
    {
        "id": "ix3-2020",
        "brandId": "bmw",
        "name": "iX3",
        "trim": "iX3",
        "range": 460,
        "battery": 73.8,
        "weightKg": 2100,
        "dragCoefficient": 0.29,
        "img": "img/cars/bmw/BMW_iX3.png",
        "power": "210 kW (286 HP)",
        "acceleration": "6.8 s (0-100 km/h)",
        "topSpeed": "200 km/h",
        "batteryType": "Li-ion",
        "driveType": "RWD",
        "charging": "150 kW DC",
        "seats": "5",
        "year": "2020-2025"
    },
    {
        "id": "ix3-sdrive-2026",
        "brandId": "bmw",
        "name": "iX3",
        "trim": "sDrive",
        "range": 700,
        "battery": 108.7,
        "weightKg": 2525,
        "dragCoefficient": 0.25,
        "img": "img/cars/bmw/BMW_iX3_2026+.png",
        "power": "235 kW (315 HP)",
        "acceleration": "5.5 s (0-100 km/h)",
        "topSpeed": "205 km/h",
        "batteryType": "NMC",
        "driveType": "RWD",
        "charging": "400 kW DC",
        "seats": "5",
        "year": "2026+"
    },
    {
        "id": "ix3-xdrive-2026",
        "brandId": "bmw",
        "name": "iX3",
        "trim": "xDrive",
        "range": 800,
        "battery": 108.7,
        "weightKg": 2580,
        "dragCoefficient": 0.25,
        "img": "img/cars/bmw/BMW_iX3_2026+.png",
        "power": "345 kW (463 HP)",
        "acceleration": "4.9 s (0-100 km/h)",
        "topSpeed": "250 km/h",
        "batteryType": "NMC",
        "driveType": "Dual Motor AWD",
        "charging": "400 kW DC",
        "seats": "5",
        "year": "2026+"
    },
    {
        "id": "ix3-m-xdrive-2026",
        "brandId": "bmw",
        "name": "iX3",
        "trim": "M xDrive",
        "range": 600,
        "battery": 108.7,
        "weightKg": 2653,
        "dragCoefficient": 0.25,
        "img": "img/cars/bmw/BMW_iX3_2026+.png",
        "power": "360 kW (490 HP)",
        "acceleration": "4.2 s (0-100 km/h)",
        "topSpeed": "250 km/h",
        "batteryType": "NMC",
        "driveType": "Dual Motor AWD",
        "charging": "400 kW DC",
        "seats": "5",
        "year": "2026+"
    }
]);
