registerCarModels([
    {
        "id": "q8-e-tron-50-2023",
        "brandId": "audi",
        "name": "Q8 e-tron",
        "trim": "50",
        "range": 505,
        "battery": 111,
        "weightKg": 2410,
        "dragCoefficient": 0.28,
        "img": "img/cars/audi/Audi_q8_e-tron.png",
        "power": "230 kW (313 HP)",
        "acceleration": "6.8 s (0-100 km/h)",
        "topSpeed": "200 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "170 kW DC",
        "seats": "5",
        "year": "2022-2024"
    },
    {
        "id": "q8-e-tron-55-2023",
        "brandId": "audi",
        "name": "Q8 e-tron",
        "trim": "55",
        "range": 582,
        "battery": 111,
        "weightKg": 2460,
        "dragCoefficient": 0.28,
        "img": "img/cars/audi/Audi_q8_e-tron.png",
        "power": "300 kW (408 HP)",
        "acceleration": "5.7 s (0-100 km/h)",
        "topSpeed": "210 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "200 kW DC",
        "seats": "5",
        "year": "2022-2024"
    },
    {
        "id": "q8-e-tron-s-2023",
        "brandId": "audi",
        "name": "Q8 e-tron",
        "trim": "S",
        "range": 530,
        "battery": 111,
        "weightKg": 2490,
        "dragCoefficient": 0.28,
        "img": "img/cars/audi/Audi_q8_e-tron.png",
        "power": "370 kW (502 HP)",
        "acceleration": "4.7 s (0-100 km/h)",
        "topSpeed": "210 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "200 kW DC",
        "seats": "5",
        "year": "2022-2024"
    }
]);
