registerCarModels([
    {
        "id": "free-82-2023",
        "brandId": "voyah",
        "name": "Free",
        "trim": "Free",
        "range": 400,
        "battery": 82,
        "weightKg": 2050,
        "dragCoefficient": 0.29,
        "img": "img/cars/voyah/Voyah_Free.png",
        "power": "230 kW (313 HP)",
        "acceleration": "6.8 s (0-100 km/h)",
        "topSpeed": "195 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "110 kW DC",
        "seats": "5",
        "year": "2023+"
    },
    {
        "id": "free-106-2023",
        "brandId": "voyah",
        "name": "Free",
        "trim": "Free",
        "range": 500,
        "battery": 106,
        "weightKg": 2080,
        "dragCoefficient": 0.29,
        "img": "img/cars/voyah/Voyah_Free.png",
        "power": "230 kW (313 HP)",
        "acceleration": "6.8 s (0-100 km/h)",
        "topSpeed": "195 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "110 kW DC",
        "seats": "5",
        "year": "2023+"
    },
    {
        "id": "free-108-2024",
        "brandId": "voyah",
        "name": "Free",
        "trim": "Free",
        "range": 510,
        "battery": 108,
        "weightKg": 2100,
        "dragCoefficient": 0.29,
        "img": "img/cars/voyah/Voyah_Free.png",
        "power": "240 kW (326 HP)",
        "acceleration": "6.6 s (0-100 km/h)",
        "topSpeed": "205 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "120 kW DC",
        "seats": "5",
        "year": "2024+"
    }
]);
