registerCarModels([
    {
        "id": "dream-82-2023",
        "brandId": "voyah",
        "name": "Dream",
        "trim": "Premium",
        "range": 420,
        "battery": 82,
        "weightKg": 2180,
        "dragCoefficient": 0.28,
        "img": "img/cars/voyah/Voyah_Dream.png",
        "power": "230 kW (313 HP)",
        "acceleration": "6.5 s (0-100 km/h)",
        "topSpeed": "200 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "120 kW DC",
        "seats": "5",
        "year": "2023+"
    },
    {
        "id": "dream-101-2023",
        "brandId": "voyah",
        "name": "Dream",
        "trim": "FlagShip",
        "range": 520,
        "battery": 108,
        "weightKg": 2200,
        "dragCoefficient": 0.28,
        "img": "img/cars/voyah/Voyah_Dream.png",
        "power": "230 kW (313 HP)",
        "acceleration": "6.5 s (0-100 km/h)",
        "topSpeed": "200 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "120 kW DC",
        "seats": "5",
        "year": "2023+"
    },
    {
        "id": "dream-108-2024",
        "brandId": "voyah",
        "name": "Dream",
        "trim": "Qinkum",
        "range": 530,
        "battery": 108,
        "weightKg": 2220,
        "dragCoefficient": 0.28,
        "img": "img/cars/voyah/Voyah_Dream.png",
        "power": "240 kW (326 HP)",
        "acceleration": "6.3 s (0-100 km/h)",
        "topSpeed": "210 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "130 kW DC",
        "seats": "5",
        "year": "2026+"
    }
]);
