window.carCatalogPromise = (async () => {
    await loadCarScriptSeries([
    "js/cars/brands/acura/logo.js",
    "js/cars/brands/audi/logo.js",
    "js/cars/brands/bmw/logo.js",
    "js/cars/brands/cadillac/logo.js",
    "js/cars/brands/dacia/logo.js",
    "js/cars/brands/honda/logo.js",
    "js/cars/brands/lexus/logo.js",
    "js/cars/brands/renault/logo.js",
    "js/cars/brands/rolls-royce/logo.js",
    "js/cars/brands/tesla/logo.js",
    "js/cars/brands/volkswagen/logo.js",
    "js/cars/brands/voyah/logo.js",
    "js/cars/brands/zeekr/logo.js"
]);
    await loadCarScriptSeries([
    "js/cars/brands/acura/models/ZDX/data.js",
    "js/cars/brands/audi/models/A6 e-tron/data.js",
    "js/cars/brands/audi/models/e-tron/data.js",
    "js/cars/brands/audi/models/e-tron GT/data.js",
    "js/cars/brands/audi/models/e-tron S/data.js",
    "js/cars/brands/audi/models/Q4 e-tron/data.js",
    "js/cars/brands/audi/models/Q6 e-tron/data.js",
    "js/cars/brands/audi/models/Q8 e-tron/data.js",
    "js/cars/brands/audi/models/S6 e-tron/data.js",
    "js/cars/brands/bmw/models/i3/data.js",
    "js/cars/brands/bmw/models/i4/data.js",
    "js/cars/brands/bmw/models/i5/data.js",
    "js/cars/brands/bmw/models/i7/data.js",
    "js/cars/brands/bmw/models/iX/data.js",
    "js/cars/brands/bmw/models/iX1/data.js",
    "js/cars/brands/bmw/models/iX2/data.js",
    "js/cars/brands/bmw/models/iX3/data.js",
    "js/cars/brands/cadillac/models/Escalade IQ/data.js",
    "js/cars/brands/cadillac/models/Lyric/data.js",
    "js/cars/brands/cadillac/models/OPTIQ/data.js",
    "js/cars/brands/cadillac/models/VISTIQ/data.js",
    "js/cars/brands/dacia/models/Spring/data.js",
    "js/cars/brands/honda/models/E/data.js",
    "js/cars/brands/honda/models/Prologue/data.js",
    "js/cars/brands/honda/models/Prologue Elite/data.js",
    "js/cars/brands/lexus/models/RZ/data.js",
    "js/cars/brands/lexus/models/UX/data.js",
    "js/cars/brands/renault/models/4 E-Tech/data.js",
    "js/cars/brands/renault/models/5 E-Tech/data.js",
    "js/cars/brands/renault/models/Kangoo E-Tech/data.js",
    "js/cars/brands/renault/models/Megane E-Tech/data.js",
    "js/cars/brands/renault/models/Scenic E-Tech/data.js",
    "js/cars/brands/renault/models/Trafic E-Tech/data.js",
    "js/cars/brands/renault/models/Twingo/data.js",
    "js/cars/brands/renault/models/Twizy/data.js",
    "js/cars/brands/renault/models/Zoe/data.js",
    "js/cars/brands/rolls-royce/models/Spectre/data.js",
    "js/cars/brands/tesla/models/Cybertruck/data.js",
    "js/cars/brands/tesla/models/Model 3/data.js",
    "js/cars/brands/tesla/models/Model S/data.js",
    "js/cars/brands/tesla/models/Model X/data.js",
    "js/cars/brands/tesla/models/Model Y/data.js",
    "js/cars/brands/volkswagen/models/e-Golf/data.js",
    "js/cars/brands/volkswagen/models/e-Up/data.js",
    "js/cars/brands/volkswagen/models/ID.1/data.js",
    "js/cars/brands/volkswagen/models/ID.3/data.js",
    "js/cars/brands/volkswagen/models/ID.4/data.js",
    "js/cars/brands/volkswagen/models/ID.5/data.js",
    "js/cars/brands/volkswagen/models/ID.6/data.js",
    "js/cars/brands/volkswagen/models/ID.7/data.js",
    "js/cars/brands/volkswagen/models/ID.Buzz/data.js",
    "js/cars/brands/voyah/models/Dream/data.js",
    "js/cars/brands/voyah/models/Free/data.js",
    "js/cars/brands/zeekr/models/001/data.js",
    "js/cars/brands/zeekr/models/7X/data.js",
    "js/cars/brands/zeekr/models/X/data.js"
]);
})();
