const carsData = [
    
//=========================================================================AUDI=======================================================================

    // ====== Q4 e-tron ======
    {
        id: 'q4-e-tron-35-2020',
        brandId: 'audi',
        name: 'Q4 e-tron',
        trim: '35',
        range: 350,
        battery: 52,
        weightKg: 1965,
        dragCoefficient: 0.28,
        img: 'img/cars/Audi_q4_e-tron.png',
        power: '125 kW (170 HP)',
        acceleration: '9.0 s (0-100 km/h)',
        topSpeed: '160 km/h',
        batteryType: 'Li-ion',
        driveType: 'RWD',
        charging: '100 kW DC',
        seats: '5',
        year: '2020+'
    },
    {
        id: 'q4-e-tron-35-2020',
        brandId: 'audi',
        name: 'Q4 e-tron',
        trim: '35',
        range: 350,
        battery: 52,
        weightKg: 1965,
        dragCoefficient: 0.28,
        img: 'img/cars/Audi_q4_e-tron.png',
        power: '125 kW (170 HP)',
        acceleration: '9.0 s (0-100 km/h)',
        topSpeed: '160 km/h',
        batteryType: 'Li-ion',
        driveType: 'RWD',
        charging: '100 kW DC',
        seats: '5',
        year: '2020+'
    },
    {
        id: 'q4-e-tron-40-2020',
        brandId: 'audi',
        name: 'Q4 e-tron',
        trim: '40',
        range: 520,
        battery: 77,
        weightKg: 2050,
        dragCoefficient: 0.28,
        img: 'img/cars/Audi_q4_e-tron.png',
        power: '150 kW (204 HP)',
        acceleration: '8.5 s (0-100 km/h)',
        topSpeed: '160 km/h',
        batteryType: 'Li-ion',
        driveType: 'RWD',
        charging: '125 kW DC',
        seats: '5',
        year: '2020+'
    },
    {
        id: 'q4-e-tron-40-sportback-2020',
        brandId: 'audi',
        name: 'Q4 e-tron',
        trim: '40 Sportback',
        range: 535,
        battery: 77,
        weightKg: 2060,
        dragCoefficient: 0.27,
        img: 'img/cars/Audi_q4_e-tron.png',
        power: '150 kW (204 HP)',
        acceleration: '8.5 s (0-100 km/h)',
        topSpeed: '160 km/h',
        batteryType: 'Li-ion',
        driveType: 'RWD',
        charging: '125 kW DC',
        seats: '5',
        year: '2020+'
    },
    {
        id: 'q4-e-tron-45-quattro-2020',
        brandId: 'audi',
        name: 'Q4 e-tron',
        trim: '45 quattro',
        range: 495,
        battery: 77,
        weightKg: 2140,
        dragCoefficient: 0.28,
        img: 'img/cars/Audi_q4_e-tron.png',
        power: '195 kW (265 HP)',
        acceleration: '6.9 s (0-100 km/h)',
        topSpeed: '180 km/h',
        batteryType: 'Li-ion',
        driveType: 'Dual Motor AWD',
        charging: '135 kW DC',
        seats: '5',
        year: '2020+'
    },
    {
        id: 'q4-e-tron-45-quattro-sportback-2020',
        brandId: 'audi',
        name: 'Q4 e-tron',
        trim: '45 quattro Sportback',
        range: 505,
        battery: 77,
        weightKg: 2150,
        dragCoefficient: 0.27,
        img: 'img/cars/Audi_q4_e-tron.png',
        power: '195 kW (265 HP)',
        acceleration: '6.9 s (0-100 km/h)',
        topSpeed: '180 km/h',
        batteryType: 'Li-ion',
        driveType: 'Dual Motor AWD',
        charging: '135 kW DC',
        seats: '5',
        year: '2020+'
    },
    {
        id: 'q4-e-tron-45-sportback-2020',
        brandId: 'audi',
        name: 'Q4 e-tron',
        trim: '45 Sportback',
        range: 540,
        battery: 77,
        weightKg: 2085,
        dragCoefficient: 0.27,
        img: 'img/cars/Audi_q4_e-tron.png',
        power: '210 kW (286 HP)',
        acceleration: '6.7 s (0-100 km/h)',
        topSpeed: '180 km/h',
        batteryType: 'Li-ion',
        driveType: 'RWD',
        charging: '135 kW DC',
        seats: '5',
        year: '2020+'
    },
    {
        id: 'q4-e-tron-50-quattro-2020',
        brandId: 'audi',
        name: 'Q4 e-tron',
        trim: '50 quattro',
        range: 490,
        battery: 77,
        weightKg: 2190,
        dragCoefficient: 0.28,
        img: 'img/cars/Audi_q4_e-tron.png',
        power: '220 kW (299 HP)',
        acceleration: '6.2 s (0-100 km/h)',
        topSpeed: '180 km/h',
        batteryType: 'Li-ion',
        driveType: 'Dual Motor AWD',
        charging: '135 kW DC',
        seats: '5',
        year: '2020+'
    },
    {
        id: 'q4-e-tron-50-quattro-sportback-2020',
        brandId: 'audi',
        name: 'Q4 e-tron',
        trim: '50 quattro Sportback',
        range: 505,
        battery: 77,
        weightKg: 2200,
        dragCoefficient: 0.27,
        img: 'img/cars/Audi_q4_e-tron.png',
        power: '220 kW (299 HP)',
        acceleration: '6.2 s (0-100 km/h)',
        topSpeed: '180 km/h',
        batteryType: 'Li-ion',
        driveType: 'Dual Motor AWD',
        charging: '135 kW DC',
        seats: '5',
        year: '2020+'
    },
    {
        id: 'q4-e-tron-55-quattro-2020',
        brandId: 'audi',
        name: 'Q4 e-tron',
        trim: '55 quattro',
        range: 470,
        battery: 77,
        weightKg: 2220,
        dragCoefficient: 0.28,
        img: 'img/cars/Audi_q4_e-tron.png',
        power: '250 kW (340 HP)',
        acceleration: '5.4 s (0-100 km/h)',
        topSpeed: '180 km/h',
        batteryType: 'Li-ion',
        driveType: 'Dual Motor AWD',
        charging: '135 kW DC',
        seats: '5',
        year: '2020+'
    },
    {
        id: 'q4-e-tron-55-quattro-sportback-2020',
        brandId: 'audi',
        name: 'Q4 e-tron',
        trim: '55 quattro Sportback',
        range: 485,
        battery: 77,
        weightKg: 2230,
        dragCoefficient: 0.27,
        img: 'img/cars/Audi_q4_e-tron.png',
        power: '250 kW (340 HP)',
        acceleration: '5.4 s (0-100 km/h)',
        topSpeed: '180 km/h',
        batteryType: 'Li-ion',
        driveType: 'Dual Motor AWD',
        charging: '135 kW DC',
        seats: '5',
        year: '2020+'
    },

    // ====== e-tron GT ======
    {
        id: 'e-tron-gt-quattro-2025',
        brandId: 'audi',
        name: 'e-tron GT',
        trim: 'quattro',
        range: 610,
        battery: 105,
        weightKg: 2380,
        dragCoefficient: 0.24,
        img: 'img/cars/Audi_e-tron_GT.png',
        power: '430 kW (585 HP)',
        acceleration: '3.6 s (0-100 km/h)',
        topSpeed: '245 km/h',
        batteryType: 'Li-ion',
        driveType: 'Dual Motor AWD',
        charging: '320 kW DC',
        seats: '4',
        year: '2025+'
    },
    {
        id: 'e-tron-gt-rs-2025',
        brandId: 'audi',
        name: 'e-tron GT',
        trim: 'RS',
        range: 575,
        battery: 105,
        weightKg: 2425,
        dragCoefficient: 0.24,
        img: 'img/cars/Audi_e-tron_GT.png',
        power: '500 kW (680 HP)',
        acceleration: '3.1 s (0-100 km/h)',
        topSpeed: '250 km/h',
        batteryType: 'Li-ion',
        driveType: 'Dual Motor AWD',
        charging: '320 kW DC',
        seats: '4',
        year: '2025+'
    },
    {
        id: 'e-tron-gt-rs-performance-2025',
        brandId: 'audi',
        name: 'e-tron GT',
        trim: 'RS Performance',
        range: 560,
        battery: 105,
        weightKg: 2460,
        dragCoefficient: 0.24,
        img: 'img/cars/Audi_e-tron_GT.png',
        power: '560 kW (761 HP)',
        acceleration: '2.8 s (0-100 km/h)',
        topSpeed: '250 km/h',
        batteryType: 'Li-ion',
        driveType: 'Dual Motor AWD',
        charging: '320 kW DC',
        seats: '4',
        year: '2025+'
    },
    {
        id: 'e-tron-gt-s-2025',
        brandId: 'audi',
        name: 'e-tron GT',
        trim: 'S',
        range: 595,
        battery: 105,
        weightKg: 2405,
        dragCoefficient: 0.24,
        img: 'img/cars/Audi_e-tron_GT.png',
        power: '500 kW (680 HP)',
        acceleration: '3.4 s (0-100 km/h)',
        topSpeed: '245 km/h',
        batteryType: 'Li-ion',
        driveType: 'Dual Motor AWD',
        charging: '320 kW DC',
        seats: '4',
        year: '2025+'
    },
    {
        id: 'e-tron-gt-quattro-2021',
        brandId: 'audi',
        name: 'e-tron GT',
        trim: 'Quattro',
        range: 488,
        battery: 96,
        weightKg: 2350,
        dragCoefficient: 0.24,
        img: 'img/cars/Audi_e-tron_GT.png',
        power: '350 kW (476 HP)',
        acceleration: '4.1 s (0-100 km/h)',
        topSpeed: '245 km/h',
        batteryType: 'Li-ion',
        driveType: 'Dual Motor AWD',
        charging: '270 kW DC',
        seats: '4',
        year: '2021-2024'
    },
    {
        id: 'e-tron-gt-rs-2021',
        brandId: 'audi',
        name: 'e-tron GT',
        trim: 'RS',
        range: 472,
        battery: 96,
        weightKg: 2395,
        dragCoefficient: 0.24,
        img: 'img/cars/Audi_e-tron_GT.png',
        power: '440 kW (598 HP)',
        acceleration: '3.3 s (0-100 km/h)',
        topSpeed: '250 km/h',
        batteryType: 'Li-ion',
        driveType: 'Dual Motor AWD',
        charging: '270 kW DC',
        seats: '4',
        year: '2021-2024'
    },

    // ====== A6 e-tron ======
    {
        id: 'a6-e-tron-40-2024',
        brandId: 'audi',
        name: 'A6 e-tron',
        trim: '40',
        range: 720,
        battery: 83,
        weightKg: 1795,
        dragCoefficient: 0.24,
        img: 'img/cars/Audi_a6_e-tron.png',
        power: '160 kW (218 HP)',
        acceleration: '8.5 s (0-100 km/h)',
        topSpeed: '200 km/h',
        batteryType: 'Li-ion',
        driveType: 'RWD',
        charging: '180 kW DC',
        seats: '5',
        year: '2024+'
    },
    {
        id: 'a6-e-tron-55-2024',
        brandId: 'audi',
        name: 'A6 e-tron',
        trim: '55',
        range: 750,
        battery: 100,
        weightKg: 1850,
        dragCoefficient: 0.24,
        img: 'img/cars/Audi_a6_e-tron.png',
        power: '270 kW (367 HP)',
        acceleration: '5.4 s (0-100 km/h)',
        topSpeed: '210 km/h',
        batteryType: 'Li-ion',
        driveType: 'RWD',
        charging: '270 kW DC',
        seats: '5',
        year: '2024+'
    },
    {
        id: 'a6-e-tron-55-quattro-2024',
        brandId: 'audi',
        name: 'A6 e-tron',
        trim: '55 quattro',
        range: 700,
        battery: 100,
        weightKg: 1950,
        dragCoefficient: 0.24,
        img: 'img/cars/Audi_a6_e-tron.png',
        power: '340 kW (462 HP)',
        acceleration: '4.5 s (0-100 km/h)',
        topSpeed: '210 km/h',
        batteryType: 'Li-ion',
        driveType: 'Dual Motor AWD',
        charging: '270 kW DC',
        seats: '5',
        year: '2024+'
    },

    // ====== e-tron ======
    {
        id: 'e-tron-50-2023',
        brandId: 'audi',
        name: 'e-tron',
        trim: '50',
        range: 450,
        battery: 83,
        weightKg: 2240,
        dragCoefficient: 0.27,
        img: 'img/cars/Audi_e-tron_s.png',
        power: '170 kW (230 HP)',
        acceleration: '8.4 s (0-100 km/h)',
        topSpeed: '200 km/h',
        batteryType: 'Li-ion',
        driveType: 'RWD',
        charging: '150 kW DC',
        seats: '5',
        year: '2019-2024'
    },
    {
        id: 'e-tron-55-2023',
        brandId: 'audi',
        name: 'e-tron',
        trim: '55',
        range: 530,
        battery: 100,
        weightKg: 2360,
        dragCoefficient: 0.27,
        img: 'img/cars/Audi_e-tron_s.png',
        power: '230 kW (313 HP)',
        acceleration: '6.3 s (0-100 km/h)',
        topSpeed: '200 km/h',
        batteryType: 'Li-ion',
        driveType: 'Dual Motor AWD',
        charging: '150 kW DC',
        seats: '5',
        year: '2019-2024'
    },
    {
        id: 'e-tron-s-2023',
        brandId: 'audi',
        name: 'e-tron',
        trim: 'S',
        range: 490,
        battery: 100,
        weightKg: 2380,
        dragCoefficient: 0.27,
        img: 'img/cars/Audi_e-tron_s.png',
        power: '370 kW (502 HP)',
        acceleration: '4.3 s (0-100 km/h)',
        topSpeed: '210 km/h',
        batteryType: 'Li-ion',
        driveType: 'Dual Motor AWD',
        charging: '150 kW DC',
        seats: '5',
        year: '2019-2024'
    },

    // ====== e-tron S ======
    {
        id: 'e-tron-s-sportback-2024',
        brandId: 'audi',
        name: 'e-tron S',
        trim: 'Sportback',
        range: 495,
        battery: 100,
        weightKg: 2390,
        dragCoefficient: 0.26,
        img: 'img/cars/Audi_e-tron_s.png',
        power: '370 kW (502 HP)',
        acceleration: '4.3 s (0-100 km/h)',
        topSpeed: '210 km/h',
        batteryType: 'Li-ion',
        driveType: 'Dual Motor AWD',
        charging: '170 kW DC',
        seats: '5',
        year: '2020-2024'
    },
    {
        id: 'e-tron-s-2024',
        brandId: 'audi',
        name: 'e-tron S',
        trim: 'Standard',
        range: 500,
        battery: 100,
        weightKg: 2390,
        dragCoefficient: 0.27,
        img: 'img/cars/Audi_e-tron_s.png',
        power: '370 kW (502 HP)',
        acceleration: '4.3 s (0-100 km/h)',
        topSpeed: '210 km/h',
        batteryType: 'Li-ion',
        driveType: 'Dual Motor AWD',
        charging: '170 kW DC',
        seats: '5',
        year: '2020-2024'
    },

    // ====== Q6 e-tron ======
    {
        id: 'q6-e-tron-40-2025',
        brandId: 'audi',
        name: 'Q6 e-tron',
        trim: '40',
        range: 645,
        battery: 100,
        weightKg: 2180,
        dragCoefficient: 0.25,
        img: 'img/cars/Audi_q6_e-tron.png',
        power: '210 kW (286 HP)',
        acceleration: '7.4 s (0-100 km/h)',
        topSpeed: '210 km/h',
        batteryType: 'Li-ion',
        driveType: 'RWD',
        charging: '270 kW DC',
        seats: '5',
        year: '2025+'
    },
    {
        id: 'q6-e-tron-55-2025',
        brandId: 'audi',
        name: 'Q6 e-tron',
        trim: '55',
        range: 700,
        battery: 100,
        weightKg: 2230,
        dragCoefficient: 0.25,
        img: 'img/cars/Audi_q6_e-tron.png',
        power: '310 kW (421 HP)',
        acceleration: '5.3 s (0-100 km/h)',
        topSpeed: '210 km/h',
        batteryType: 'Li-ion',
        driveType: 'RWD',
        charging: '270 kW DC',
        seats: '5',
        year: '2025+'
    },
    {
        id: 'q6-e-tron-55-quattro-2025',
        brandId: 'audi',
        name: 'Q6 e-tron',
        trim: '55 quattro',
        range: 680,
        battery: 100,
        weightKg: 2380,
        dragCoefficient: 0.25,
        img: 'img/cars/Audi_q6_e-tron.png',
        power: '380 kW (516 HP)',
        acceleration: '4.8 s (0-100 km/h)',
        topSpeed: '210 km/h',
        batteryType: 'Li-ion',
        driveType: 'Dual Motor AWD',
        charging: '270 kW DC',
        seats: '5',
        year: '2025+'
    },

    // ====== Q8 e-tron ======
    {
        id: 'q8-e-tron-50-2023',
        brandId: 'audi',
        name: 'Q8 e-tron',
        trim: '50',
        range: 505,
        battery: 111,
        weightKg: 2410,
        dragCoefficient: 0.28,
        img: 'img/cars/Audi_q8_e-tron.png',
        power: '230 kW (313 HP)',
        acceleration: '6.8 s (0-100 km/h)',
        topSpeed: '200 km/h',
        batteryType: 'Li-ion',
        driveType: 'Dual Motor AWD',
        charging: '170 kW DC',
        seats: '5',
        year: '2022-2024'
    },
    {
        id: 'q8-e-tron-55-2023',
        brandId: 'audi',
        name: 'Q8 e-tron',
        trim: '55',
        range: 582,
        battery: 111,
        weightKg: 2460,
        dragCoefficient: 0.28,
        img: 'img/cars/Audi_q8_e-tron.png',
        power: '300 kW (408 HP)',
        acceleration: '5.7 s (0-100 km/h)',
        topSpeed: '210 km/h',
        batteryType: 'Li-ion',
        driveType: 'Dual Motor AWD',
        charging: '200 kW DC',
        seats: '5',
        year: '2022-2024'
    },
    {
        id: 'q8-e-tron-s-2023',
        brandId: 'audi',
        name: 'Q8 e-tron',
        trim: 'S',
        range: 530,
        battery: 111,
        weightKg: 2490,
        dragCoefficient: 0.28,
        img: 'img/cars/Audi_q8_e-tron.png',
        power: '370 kW (502 HP)',
        acceleration: '4.7 s (0-100 km/h)',
        topSpeed: '210 km/h',
        batteryType: 'Li-ion',
        driveType: 'Dual Motor AWD',
        charging: '200 kW DC',
        seats: '5',
        year: '2022-2024'
    },

    // ====== S6 e-tron ======
    {
        id: 's6-e-tron-2025',
        brandId: 'audi',
        name: 'S6 e-tron',
        trim: 'Standard',
        range: 680,
        battery: 100,
        weightKg: 2060,
        dragCoefficient: 0.24,
        img: 'img/cars/Audi_s6_e-tron.png',
        power: '430 kW (585 HP)',
        acceleration: '3.8 s (0-100 km/h)',
        topSpeed: '230 km/h',
        batteryType: 'Li-ion',
        driveType: 'Dual Motor AWD',
        charging: '270 kW DC',
        seats: '5',
        year: '2025+'
    },
    {
        id: 's6-e-tron-plus-2025',
        brandId: 'audi',
        name: 'S6 e-tron',
        trim: 'Plus',
        range: 720,
        battery: 100,
        weightKg: 2080,
        dragCoefficient: 0.24,
        img: 'img/cars/Audi_s6_e-tron.png',
        power: '430 kW (585 HP)',
        acceleration: '3.7 s (0-100 km/h)',
        topSpeed: '230 km/h',
        batteryType: 'Li-ion',
        driveType: 'Dual Motor AWD',
        charging: '270 kW DC',
        seats: '5',
        year: '2025+'
    },

//=========================================================================LEXUS=======================================================================

    // ====== RZ ======
    // 2026+
    {
        id: 'rz-350e-2026',
        brandId: 'lexus',
        name: 'RZ',
        trim: '350e',
        range: 350,
        battery: 77,
        weightKg: 2080,
        dragCoefficient: 0.28,
        img: 'img/cars/Lexus_rz_2026.png',
        power: '150 kW (204 HP)',
        acceleration: '8.2 s (0-100 km/h)',
        topSpeed: '170 km/h',
        batteryType: 'Li-ion',
        driveType: 'RWD',
        charging: '150 kW DC',
        seats: '5',
        year: '2026+'
    },
    {
        id: 'rz-500e-2026',
        brandId: 'lexus',
        name: 'RZ',
        trim: '500e',
        range: 430,
        battery: 77,
        weightKg: 2150,
        dragCoefficient: 0.28,
        img: 'img/cars/Lexus_rz_2026.png',
        power: '230 kW (313 HP)',
        acceleration: '5.6 s (0-100 km/h)',
        topSpeed: '180 km/h',
        batteryType: 'Li-ion',
        driveType: 'Dual Motor AWD',
        charging: '150 kW DC',
        seats: '5',
        year: '2026+'
    },
    {
        id: 'rz-550e-f-sport-2026',
        brandId: 'lexus',
        name: 'RZ',
        trim: '550e F SPORT',
        range: 410,
        battery: 77,
        weightKg: 2180,
        dragCoefficient: 0.28,
        img: 'img/cars/Lexus_rz_2026.png',
        power: '270 kW (367 HP)',
        acceleration: '4.8 s (0-100 km/h)',
        topSpeed: '190 km/h',
        batteryType: 'Li-ion',
        driveType: 'Dual Motor AWD',
        charging: '150 kW DC',
        seats: '5',
        year: '2026+'
    },
    {
        id: 'rz-600e-f-sport-2026',
        brandId: 'lexus',
        name: 'RZ',
        trim: '600e F SPORT',
        range: 390,
        battery: 77,
        weightKg: 2210,
        dragCoefficient: 0.28,
        img: 'img/cars/Lexus_rz_2026.png',
        power: '310 kW (421 HP)',
        acceleration: '4.2 s (0-100 km/h)',
        topSpeed: '200 km/h',
        batteryType: 'Li-ion',
        driveType: 'Dual Motor AWD',
        charging: '150 kW DC',
        seats: '5',
        year: '2026+'
    },
    // 2024-2025
    {
        id: 'rz-300e-2024',
        brandId: 'lexus',
        name: 'RZ',
        trim: '300e',
        range: 315,
        battery: 64,
        weightKg: 2000,
        dragCoefficient: 0.28,
        img: 'img/cars/Lexus_rz.png',
        power: '130 kW (177 HP)',
        acceleration: '9.0 s (0-100 km/h)',
        topSpeed: '160 km/h',
        batteryType: 'Li-ion',
        driveType: 'FWD',
        charging: '100 kW DC',
        seats: '5',
        year: '2024-2025'
    },
    // 2023-2025
    {
        id: 'rz-450e-2023',
        brandId: 'lexus',
        name: 'RZ',
        trim: '450e',
        range: 395,
        battery: 64,
        weightKg: 2105,
        dragCoefficient: 0.28,
        img: 'img/cars/Lexus_rz.png',
        power: '230 kW (313 HP)',
        acceleration: '5.6 s (0-100 km/h)',
        topSpeed: '180 km/h',
        batteryType: 'Li-ion',
        driveType: 'Dual Motor AWD',
        charging: '150 kW DC',
        seats: '5',
        year: '2023-2025'
    },

    // ====== UX ======
    {
        id: 'ux-300e-2023',
        brandId: 'lexus',
        name: 'UX',
        trim: '300e',
        range: 450,
        battery: 73,
        weightKg: 1840,
        dragCoefficient: 0.31,
        img: 'img/cars/Lexus_ux.png',
        power: '150 kW (204 HP)',
        acceleration: '7.5 s (0-100 km/h)',
        topSpeed: '160 km/h',
        batteryType: 'Li-ion',
        driveType: 'FWD',
        charging: '50 kW DC',
        seats: '5',
        year: '2023+'
    },

//=========================================================================HONDA=======================================================================

    // ====== e ======
    {
        id: 'honda-e-2020',
        brandId: 'honda',
        name: 'E',
        trim: 'Advance',
        range: 220,
        battery: 35,
        weightKg: 1525,
        dragCoefficient: 0.30,
        img: 'img/cars/Honda_e.png',
        power: '113 kW (154 HP)',
        acceleration: '8.3 s (0-100 km/h)',
        topSpeed: '145 km/h',
        batteryType: 'Li-ion',
        driveType: 'RWD',
        charging: '56 kW DC',
        seats: '4',
        year: '2020+'
    },

    // ====== Prologue ======
    {
        id: 'prologue-ex-awd-2024',
        brandId: 'honda',
        name: 'Prologue',
        trim: 'EX AWD',
        range: 452,
        battery: 85,
        weightKg: 2260,
        dragCoefficient: 0.30,
        img: 'img/cars/Honda_prologue_elite.png',
        power: '212 kW (288 HP)',
        acceleration: '6.5 s (0-100 km/h)',
        topSpeed: '180 km/h',
        batteryType: 'Li-ion',
        driveType: 'Dual Motor AWD',
        charging: '150 kW DC',
        seats: '5',
        year: '2024+'
    },

    // ====== Prologue Elite ======
    {
        id: 'prologue-elite-awd-2024',
        brandId: 'honda',
        name: 'Prologue Elite',
        trim: 'AWD',
        range: 438,
        battery: 85,
        weightKg: 2290,
        dragCoefficient: 0.30,
        img: 'img/cars/Honda_prologue_elite.png',
        power: '212 kW (288 HP)',
        acceleration: '6.5 s (0-100 km/h)',
        topSpeed: '180 km/h',
        batteryType: 'Li-ion',
        driveType: 'Dual Motor AWD',
        charging: '150 kW DC',
        seats: '5',
        year: '2024+'
    },

//=========================================================================ZEEKR=======================================================================

    // ====== 001 ======
    {
        id: 'zeekr-001-long-range-rwd-2024',
        brandId: 'zeekr',
        name: '001',
        trim: 'Long Range RWD',
        range: 620,
        battery: 100,
        weightKg: 2150,
        dragCoefficient: 0.27,
        img: 'img/cars/Zeekr_001.png',
        power: '150 kW (204 HP)',
        acceleration: '7.5 s (0-100 km/h)',
        topSpeed: '190 km/h',
        batteryType: 'Li-ion LFP',
        driveType: 'RWD',
        charging: '200 kW DC',
        seats: '5',
        year: '2024+'
    },
    {
        id: 'zeekr-001-performance-awd-2024',
        brandId: 'zeekr',
        name: '001',
        trim: 'Performance AWD',
        range: 580,
        battery: 100,
        weightKg: 2180,
        dragCoefficient: 0.27,
        img: 'img/cars/Zeekr_001.png',
        power: '290 kW (394 HP)',
        acceleration: '5.0 s (0-100 km/h)',
        topSpeed: '210 km/h',
        batteryType: 'Li-ion LFP',
        driveType: 'Dual Motor AWD',
        charging: '200 kW DC',
        seats: '5',
        year: '2024+'
    },
    {
        id: 'zeekr-001-privilege-awd-2024',
        brandId: 'zeekr',
        name: '001',
        trim: 'Privilege AWD',
        range: 580,
        battery: 100,
        weightKg: 2200,
        dragCoefficient: 0.27,
        img: 'img/cars/Zeekr_001.png',
        power: '290 kW (394 HP)',
        acceleration: '5.0 s (0-100 km/h)',
        topSpeed: '210 km/h',
        batteryType: 'Li-ion LFP',
        driveType: 'Dual Motor AWD',
        charging: '200 kW DC',
        seats: '5',
        year: '2024+'
    },

    // ====== 7X ======
    {
        id: 'zeekr-7x-long-range-2025',
        brandId: 'zeekr',
        name: '7X',
        trim: 'Long Range',
        range: 670,
        battery: 94,
        weightKg: 2480,
        dragCoefficient: 0.28,
        img: 'img/cars/Zeekr_7x.png',
        power: '230 kW (313 HP)',
        acceleration: '5.8 s (0-100 km/h)',
        topSpeed: '210 km/h',
        batteryType: 'Li-ion LFP',
        driveType: 'Dual Motor AWD',
        charging: '200 kW DC',
        seats: '7',
        year: '2025+'
    },
    {
        id: 'zeekr-7x-performance-2025',
        brandId: 'zeekr',
        name: '7X',
        trim: 'Performance',
        range: 650,
        battery: 94,
        weightKg: 2500,
        dragCoefficient: 0.28,
        img: 'img/cars/Zeekr_7x.png',
        power: '280 kW (380 HP)',
        acceleration: '5.3 s (0-100 km/h)',
        topSpeed: '220 km/h',
        batteryType: 'Li-ion LFP',
        driveType: 'Dual Motor AWD',
        charging: '200 kW DC',
        seats: '7',
        year: '2025+'
    },
    {
        id: 'zeekr-7x-premium-rwd-2025',
        brandId: 'zeekr',
        name: '7X',
        trim: 'Premium RWD',
        range: 480,
        battery: 71,
        weightKg: 2380,
        dragCoefficient: 0.28,
        img: 'img/cars/Zeekr_7x.png',
        power: '160 kW (218 HP)',
        acceleration: '7.2 s (0-100 km/h)',
        topSpeed: '190 km/h',
        batteryType: 'Li-ion LFP',
        driveType: 'RWD',
        charging: '150 kW DC',
        seats: '7',
        year: '2025+'
    },

    // ====== X ======
    {
        id: 'zeekr-x-long-range-rwd-2024',
        brandId: 'zeekr',
        name: 'X',
        trim: 'Long Range RWD',
        range: 480,
        battery: 69,
        weightKg: 1650,
        dragCoefficient: 0.29,
        img: 'img/cars/Zeekr_X.png',
        power: '140 kW (190 HP)',
        acceleration: '8.0 s (0-100 km/h)',
        topSpeed: '180 km/h',
        batteryType: 'Li-ion LFP',
        driveType: 'RWD',
        charging: '150 kW DC',
        seats: '5',
        year: '2024+'
    },
    {
        id: 'zeekr-x-privilege-awd-2024',
        brandId: 'zeekr',
        name: 'X',
        trim: 'Privilege AWD',
        range: 450,
        battery: 69,
        weightKg: 1700,
        dragCoefficient: 0.29,
        img: 'img/cars/Zeekr_X.png',
        power: '230 kW (313 HP)',
        acceleration: '6.5 s (0-100 km/h)',
        topSpeed: '200 km/h',
        batteryType: 'Li-ion LFP',
        driveType: 'Dual Motor AWD',
        charging: '150 kW DC',
        seats: '5',
        year: '2024+'
    },

//=========================================================================CADILLAC=======================================================================

    // ====== Escalade IQ ======
    {
        id: 'escalade-iq-2024',
        brandId: 'cadillac',
        name: 'Escalade IQ',
        trim: 'Standard',
        range: 500,
        battery: 200,
        weightKg: 2680,
        dragCoefficient: 0.35,
        img: 'img/cars/Cadillac_Escalade_IQ.png',
        power: '450 kW (612 HP)',
        acceleration: '4.5 s (0-100 km/h)',
        topSpeed: '210 km/h',
        batteryType: 'Li-ion',
        driveType: 'Dual Motor AWD',
        charging: '200 kW DC',
        seats: '8',
        year: '2024+'
    },

    // ====== Lyric ======
    {
        id: 'lyric-awd-2022',
        brandId: 'cadillac',
        name: 'Lyric',
        trim: 'AWD',
        range: 480,
        battery: 102,
        weightKg: 2180,
        dragCoefficient: 0.30,
        img: 'img/cars/Cadillac_Lyric.png',
        power: '340 kW (462 HP)',
        acceleration: '5.5 s (0-100 km/h)',
        topSpeed: '210 km/h',
        batteryType: 'Li-ion',
        driveType: 'Dual Motor AWD',
        charging: '150 kW DC',
        seats: '5',
        year: '2022+'
    },
    {
        id: 'lyric-rwd-2022',
        brandId: 'cadillac',
        name: 'Lyric',
        trim: 'RWD',
        range: 520,
        battery: 102,
        weightKg: 2120,
        dragCoefficient: 0.30,
        img: 'img/cars/Cadillac_Lyric.png',
        power: '255 kW (340 HP)',
        acceleration: '6.0 s (0-100 km/h)',
        topSpeed: '200 km/h',
        batteryType: 'Li-ion',
        driveType: 'RWD',
        charging: '150 kW DC',
        seats: '5',
        year: '2022+'
    },

    // ====== OPTIQ ======
    {
        id: 'optiq-luxury-2025',
        brandId: 'cadillac',
        name: 'OPTIQ',
        trim: 'Luxury',
        range: 450,
        battery: 85,
        weightKg: 2000,
        dragCoefficient: 0.31,
        img: 'img/cars/Cadillac_OPTIQ.png',
        power: '280 kW (380 HP)',
        acceleration: '5.8 s (0-100 km/h)',
        topSpeed: '200 km/h',
        batteryType: 'Li-ion',
        driveType: 'Dual Motor AWD',
        charging: '135 kW DC',
        seats: '5',
        year: '2025+'
    },
    {
        id: 'optiq-sport-2025',
        brandId: 'cadillac',
        name: 'OPTIQ',
        trim: 'Sport',
        range: 440,
        battery: 85,
        weightKg: 2010,
        dragCoefficient: 0.31,
        img: 'img/cars/Cadillac_OPTIQ.png',
        power: '280 kW (380 HP)',
        acceleration: '5.8 s (0-100 km/h)',
        topSpeed: '200 km/h',
        batteryType: 'Li-ion',
        driveType: 'Dual Motor AWD',
        charging: '135 kW DC',
        seats: '5',
        year: '2025+'
    },

    // ====== VISTIQ ======
    {
        id: 'vistiq-luxury-2025',
        brandId: 'cadillac',
        name: 'VISTIQ',
        trim: 'Luxury',
        range: 530,
        battery: 102,
        weightKg: 2380,
        dragCoefficient: 0.32,
        img: 'img/cars/Cadillac_VISTIQ.png',
        power: '310 kW (421 HP)',
        acceleration: '5.2 s (0-100 km/h)',
        topSpeed: '210 km/h',
        batteryType: 'Li-ion',
        driveType: 'Dual Motor AWD',
        charging: '170 kW DC',
        seats: '7',
        year: '2025+'
    },
    {
        id: 'vistiq-sport-2025',
        brandId: 'cadillac',
        name: 'VISTIQ',
        trim: 'Sport',
        range: 510,
        battery: 102,
        weightKg: 2400,
        dragCoefficient: 0.32,
        img: 'img/cars/Cadillac_VISTIQ.png',
        power: '340 kW (462 HP)',
        acceleration: '4.8 s (0-100 km/h)',
        topSpeed: '220 km/h',
        batteryType: 'Li-ion',
        driveType: 'Dual Motor AWD',
        charging: '170 kW DC',
        seats: '7',
        year: '2025+'
    },

];