const carsData = [
    
//=========================================================================AUDI=======================================================================

    // ====== Q4 e-tron ======
    {
        id: 'q4-e-tron-35-2020',
        brandId: 'audi',
        name: 'Q4 e-tron',
        trim: '35',
        range: 350,
        battery: 52,
        weightKg: 1965,
        dragCoefficient: 0.28,
        img: 'img/cars/Audi_q4_e-tron.png',
        power: '125 kW (170 HP)',
        acceleration: '9.0 s (0-100 km/h)',
        topSpeed: '160 km/h',
        batteryType: 'Li-ion',
        driveType: 'RWD',
        charging: '100 kW DC',
        seats: '5',
        year: '2020+'
    },
    {
        id: 'q4-e-tron-35-2020',
        brandId: 'audi',
        name: 'Q4 e-tron',
        trim: '35',
        range: 350,
        battery: 52,
        weightKg: 1965,
        dragCoefficient: 0.28,
        img: 'img/cars/Audi_q4_e-tron.png',
        power: '125 kW (170 HP)',
        acceleration: '9.0 s (0-100 km/h)',
        topSpeed: '160 km/h',
        batteryType: 'Li-ion',
        driveType: 'RWD',
        charging: '100 kW DC',
        seats: '5',
        year: '2020+'
    },
    {
        id: 'q4-e-tron-40-2020',
        brandId: 'audi',
        name: 'Q4 e-tron',
        trim: '40',
        range: 520,
        battery: 77,
        weightKg: 2050,
        dragCoefficient: 0.28,
        img: 'img/cars/Audi_q4_e-tron.png',
        power: '150 kW (204 HP)',
        acceleration: '8.5 s (0-100 km/h)',
        topSpeed: '160 km/h',
        batteryType: 'Li-ion',
        driveType: 'RWD',
        charging: '125 kW DC',
        seats: '5',
        year: '2020+'
    },
    {
        id: 'q4-e-tron-40-sportback-2020',
        brandId: 'audi',
        name: 'Q4 e-tron',
        trim: '40 Sportback',
        range: 535,
        battery: 77,
        weightKg: 2060,
        dragCoefficient: 0.27,
        img: 'img/cars/Audi_q4_e-tron.png',
        power: '150 kW (204 HP)',
        acceleration: '8.5 s (0-100 km/h)',
        topSpeed: '160 km/h',
        batteryType: 'Li-ion',
        driveType: 'RWD',
        charging: '125 kW DC',
        seats: '5',
        year: '2020+'
    },
    {
        id: 'q4-e-tron-45-quattro-2020',
        brandId: 'audi',
        name: 'Q4 e-tron',
        trim: '45 quattro',
        range: 495,
        battery: 77,
        weightKg: 2140,
        dragCoefficient: 0.28,
        img: 'img/cars/Audi_q4_e-tron.png',
        power: '195 kW (265 HP)',
        acceleration: '6.9 s (0-100 km/h)',
        topSpeed: '180 km/h',
        batteryType: 'Li-ion',
        driveType: 'Dual Motor AWD',
        charging: '135 kW DC',
        seats: '5',
        year: '2020+'
    },
    {
        id: 'q4-e-tron-45-quattro-sportback-2020',
        brandId: 'audi',
        name: 'Q4 e-tron',
        trim: '45 quattro Sportback',
        range: 505,
        battery: 77,
        weightKg: 2150,
        dragCoefficient: 0.27,
        img: 'img/cars/Audi_q4_e-tron.png',
        power: '195 kW (265 HP)',
        acceleration: '6.9 s (0-100 km/h)',
        topSpeed: '180 km/h',
        batteryType: 'Li-ion',
        driveType: 'Dual Motor AWD',
        charging: '135 kW DC',
        seats: '5',
        year: '2020+'
    },
    {
        id: 'q4-e-tron-45-sportback-2020',
        brandId: 'audi',
        name: 'Q4 e-tron',
        trim: '45 Sportback',
        range: 540,
        battery: 77,
        weightKg: 2085,
        dragCoefficient: 0.27,
        img: 'img/cars/Audi_q4_e-tron.png',
        power: '210 kW (286 HP)',
        acceleration: '6.7 s (0-100 km/h)',
        topSpeed: '180 km/h',
        batteryType: 'Li-ion',
        driveType: 'RWD',
        charging: '135 kW DC',
        seats: '5',
        year: '2020+'
    },
    {
        id: 'q4-e-tron-50-quattro-2020',
        brandId: 'audi',
        name: 'Q4 e-tron',
        trim: '50 quattro',
        range: 490,
        battery: 77,
        weightKg: 2190,
        dragCoefficient: 0.28,
        img: 'img/cars/Audi_q4_e-tron.png',
        power: '220 kW (299 HP)',
        acceleration: '6.2 s (0-100 km/h)',
        topSpeed: '180 km/h',
        batteryType: 'Li-ion',
        driveType: 'Dual Motor AWD',
        charging: '135 kW DC',
        seats: '5',
        year: '2020+'
    },
    {
        id: 'q4-e-tron-50-quattro-sportback-2020',
        brandId: 'audi',
        name: 'Q4 e-tron',
        trim: '50 quattro Sportback',
        range: 505,
        battery: 77,
        weightKg: 2200,
        dragCoefficient: 0.27,
        img: 'img/cars/Audi_q4_e-tron.png',
        power: '220 kW (299 HP)',
        acceleration: '6.2 s (0-100 km/h)',
        topSpeed: '180 km/h',
        batteryType: 'Li-ion',
        driveType: 'Dual Motor AWD',
        charging: '135 kW DC',
        seats: '5',
        year: '2020+'
    },
    {
        id: 'q4-e-tron-55-quattro-2020',
        brandId: 'audi',
        name: 'Q4 e-tron',
        trim: '55 quattro',
        range: 470,
        battery: 77,
        weightKg: 2220,
        dragCoefficient: 0.28,
        img: 'img/cars/Audi_q4_e-tron.png',
        power: '250 kW (340 HP)',
        acceleration: '5.4 s (0-100 km/h)',
        topSpeed: '180 km/h',
        batteryType: 'Li-ion',
        driveType: 'Dual Motor AWD',
        charging: '135 kW DC',
        seats: '5',
        year: '2020+'
    },
    {
        id: 'q4-e-tron-55-quattro-sportback-2020',
        brandId: 'audi',
        name: 'Q4 e-tron',
        trim: '55 quattro Sportback',
        range: 485,
        battery: 77,
        weightKg: 2230,
        dragCoefficient: 0.27,
        img: 'img/cars/Audi_q4_e-tron.png',
        power: '250 kW (340 HP)',
        acceleration: '5.4 s (0-100 km/h)',
        topSpeed: '180 km/h',
        batteryType: 'Li-ion',
        driveType: 'Dual Motor AWD',
        charging: '135 kW DC',
        seats: '5',
        year: '2020+'
    },

    // ====== e-tron GT ======
    {
        id: 'e-tron-gt-quattro-2025',
        brandId: 'audi',
        name: 'e-tron GT',
        trim: 'quattro',
        range: 610,
        battery: 105,
        weightKg: 2380,
        dragCoefficient: 0.24,
        img: 'img/cars/Audi_e-tron_GT.png',
        power: '430 kW (585 HP)',
        acceleration: '3.6 s (0-100 km/h)',
        topSpeed: '245 km/h',
        batteryType: 'Li-ion',
        driveType: 'Dual Motor AWD',
        charging: '320 kW DC',
        seats: '4',
        year: '2025+'
    },
    {
        id: 'e-tron-gt-rs-2025',
        brandId: 'audi',
        name: 'e-tron GT',
        trim: 'RS',
        range: 575,
        battery: 105,
        weightKg: 2425,
        dragCoefficient: 0.24,
        img: 'img/cars/Audi_e-tron_GT.png',
        power: '500 kW (680 HP)',
        acceleration: '3.1 s (0-100 km/h)',
        topSpeed: '250 km/h',
        batteryType: 'Li-ion',
        driveType: 'Dual Motor AWD',
        charging: '320 kW DC',
        seats: '4',
        year: '2025+'
    },
    {
        id: 'e-tron-gt-rs-performance-2025',
        brandId: 'audi',
        name: 'e-tron GT',
        trim: 'RS Performance',
        range: 560,
        battery: 105,
        weightKg: 2460,
        dragCoefficient: 0.24,
        img: 'img/cars/Audi_e-tron_GT.png',
        power: '560 kW (761 HP)',
        acceleration: '2.8 s (0-100 km/h)',
        topSpeed: '250 km/h',
        batteryType: 'Li-ion',
        driveType: 'Dual Motor AWD',
        charging: '320 kW DC',
        seats: '4',
        year: '2025+'
    },
    {
        id: 'e-tron-gt-s-2025',
        brandId: 'audi',
        name: 'e-tron GT',
        trim: 'S',
        range: 595,
        battery: 105,
        weightKg: 2405,
        dragCoefficient: 0.24,
        img: 'img/cars/Audi_e-tron_GT.png',
        power: '500 kW (680 HP)',
        acceleration: '3.4 s (0-100 km/h)',
        topSpeed: '245 km/h',
        batteryType: 'Li-ion',
        driveType: 'Dual Motor AWD',
        charging: '320 kW DC',
        seats: '4',
        year: '2025+'
    },
    {
        id: 'e-tron-gt-quattro-2021',
        brandId: 'audi',
        name: 'e-tron GT',
        trim: 'Quattro',
        range: 488,
        battery: 96,
        weightKg: 2350,
        dragCoefficient: 0.24,
        img: 'img/cars/Audi_e-tron_GT.png',
        power: '350 kW (476 HP)',
        acceleration: '4.1 s (0-100 km/h)',
        topSpeed: '245 km/h',
        batteryType: 'Li-ion',
        driveType: 'Dual Motor AWD',
        charging: '270 kW DC',
        seats: '4',
        year: '2021-2024'
    },
    {
        id: 'e-tron-gt-rs-2021',
        brandId: 'audi',
        name: 'e-tron GT',
        trim: 'RS',
        range: 472,
        battery: 96,
        weightKg: 2395,
        dragCoefficient: 0.24,
        img: 'img/cars/Audi_e-tron_GT.png',
        power: '440 kW (598 HP)',
        acceleration: '3.3 s (0-100 km/h)',
        topSpeed: '250 km/h',
        batteryType: 'Li-ion',
        driveType: 'Dual Motor AWD',
        charging: '270 kW DC',
        seats: '4',
        year: '2021-2024'
    },

    // ====== A6 e-tron ======
    {
        id: 'a6-e-tron-40-2024',
        brandId: 'audi',
        name: 'A6 e-tron',
        trim: '40',
        range: 720,
        battery: 83,
        weightKg: 1795,
        dragCoefficient: 0.24,
        img: 'img/cars/Audi_a6_e-tron.png',
        power: '160 kW (218 HP)',
        acceleration: '8.5 s (0-100 km/h)',
        topSpeed: '200 km/h',
        batteryType: 'Li-ion',
        driveType: 'RWD',
        charging: '180 kW DC',
        seats: '5',
        year: '2024+'
    },
    {
        id: 'a6-e-tron-55-2024',
        brandId: 'audi',
        name: 'A6 e-tron',
        trim: '55',
        range: 750,
        battery: 100,
        weightKg: 1850,
        dragCoefficient: 0.24,
        img: 'img/cars/Audi_a6_e-tron.png',
        power: '270 kW (367 HP)',
        acceleration: '5.4 s (0-100 km/h)',
        topSpeed: '210 km/h',
        batteryType: 'Li-ion',
        driveType: 'RWD',
        charging: '270 kW DC',
        seats: '5',
        year: '2024+'
    },
    {
        id: 'a6-e-tron-55-quattro-2024',
        brandId: 'audi',
        name: 'A6 e-tron',
        trim: '55 quattro',
        range: 700,
        battery: 100,
        weightKg: 1950,
        dragCoefficient: 0.24,
        img: 'img/cars/Audi_a6_e-tron.png',
        power: '340 kW (462 HP)',
        acceleration: '4.5 s (0-100 km/h)',
        topSpeed: '210 km/h',
        batteryType: 'Li-ion',
        driveType: 'Dual Motor AWD',
        charging: '270 kW DC',
        seats: '5',
        year: '2024+'
    },

    // ====== e-tron ======
    {
        id: 'e-tron-50-2023',
        brandId: 'audi',
        name: 'e-tron',
        trim: '50',
        range: 450,
        battery: 83,
        weightKg: 2240,
        dragCoefficient: 0.27,
        img: 'img/cars/Audi_e-tron.png',
        power: '170 kW (230 HP)',
        acceleration: '8.4 s (0-100 km/h)',
        topSpeed: '200 km/h',
        batteryType: 'Li-ion',
        driveType: 'RWD',
        charging: '150 kW DC',
        seats: '5',
        year: '2019-2024'
    },
    {
        id: 'e-tron-55-2023',
        brandId: 'audi',
        name: 'e-tron',
        trim: '55',
        range: 530,
        battery: 100,
        weightKg: 2360,
        dragCoefficient: 0.27,
        img: 'img/cars/Audi_e-tron.png',
        power: '230 kW (313 HP)',
        acceleration: '6.3 s (0-100 km/h)',
        topSpeed: '200 km/h',
        batteryType: 'Li-ion',
        driveType: 'Dual Motor AWD',
        charging: '150 kW DC',
        seats: '5',
        year: '2019-2024'
    },
    {
        id: 'e-tron-s-2023',
        brandId: 'audi',
        name: 'e-tron',
        trim: 'S',
        range: 490,
        battery: 100,
        weightKg: 2380,
        dragCoefficient: 0.27,
        img: 'img/cars/Audi_e-tron.png',
        power: '370 kW (502 HP)',
        acceleration: '4.3 s (0-100 km/h)',
        topSpeed: '210 km/h',
        batteryType: 'Li-ion',
        driveType: 'Dual Motor AWD',
        charging: '150 kW DC',
        seats: '5',
        year: '2019-2024'
    },

    // ====== e-tron S ======
    {
        id: 'e-tron-s-sportback-2024',
        brandId: 'audi',
        name: 'e-tron S',
        trim: 'Sportback',
        range: 495,
        battery: 100,
        weightKg: 2390,
        dragCoefficient: 0.26,
        img: 'img/cars/Audi_e-tron_s.png',
        power: '370 kW (502 HP)',
        acceleration: '4.3 s (0-100 km/h)',
        topSpeed: '210 km/h',
        batteryType: 'Li-ion',
        driveType: 'Dual Motor AWD',
        charging: '170 kW DC',
        seats: '5',
        year: '2020-2024'
    },
    {
        id: 'e-tron-s-2024',
        brandId: 'audi',
        name: 'e-tron S',
        trim: 'Standard',
        range: 500,
        battery: 100,
        weightKg: 2390,
        dragCoefficient: 0.27,
        img: 'img/cars/Audi_e-tron_s.png',
        power: '370 kW (502 HP)',
        acceleration: '4.3 s (0-100 km/h)',
        topSpeed: '210 km/h',
        batteryType: 'Li-ion',
        driveType: 'Dual Motor AWD',
        charging: '170 kW DC',
        seats: '5',
        year: '2020-2024'
    },

    // ====== Q6 e-tron ======
    {
        id: 'q6-e-tron-40-2025',
        brandId: 'audi',
        name: 'Q6 e-tron',
        trim: '40',
        range: 645,
        battery: 100,
        weightKg: 2180,
        dragCoefficient: 0.25,
        img: 'img/cars/Audi_q6_e-tron.png',
        power: '210 kW (286 HP)',
        acceleration: '7.4 s (0-100 km/h)',
        topSpeed: '210 km/h',
        batteryType: 'Li-ion',
        driveType: 'RWD',
        charging: '270 kW DC',
        seats: '5',
        year: '2025+'
    },
    {
        id: 'q6-e-tron-55-2025',
        brandId: 'audi',
        name: 'Q6 e-tron',
        trim: '55',
        range: 700,
        battery: 100,
        weightKg: 2230,
        dragCoefficient: 0.25,
        img: 'img/cars/Audi_q6_e-tron.png',
        power: '310 kW (421 HP)',
        acceleration: '5.3 s (0-100 km/h)',
        topSpeed: '210 km/h',
        batteryType: 'Li-ion',
        driveType: 'RWD',
        charging: '270 kW DC',
        seats: '5',
        year: '2025+'
    },
    {
        id: 'q6-e-tron-55-quattro-2025',
        brandId: 'audi',
        name: 'Q6 e-tron',
        trim: '55 quattro',
        range: 680,
        battery: 100,
        weightKg: 2380,
        dragCoefficient: 0.25,
        img: 'img/cars/Audi_q6_e-tron.png',
        power: '380 kW (516 HP)',
        acceleration: '4.8 s (0-100 km/h)',
        topSpeed: '210 km/h',
        batteryType: 'Li-ion',
        driveType: 'Dual Motor AWD',
        charging: '270 kW DC',
        seats: '5',
        year: '2025+'
    },

    // ====== Q8 e-tron ======
    {
        id: 'q8-e-tron-50-2023',
        brandId: 'audi',
        name: 'Q8 e-tron',
        trim: '50',
        range: 505,
        battery: 111,
        weightKg: 2410,
        dragCoefficient: 0.28,
        img: 'img/cars/Audi_q8_e-tron.png',
        power: '230 kW (313 HP)',
        acceleration: '6.8 s (0-100 km/h)',
        topSpeed: '200 km/h',
        batteryType: 'Li-ion',
        driveType: 'Dual Motor AWD',
        charging: '170 kW DC',
        seats: '5',
        year: '2022-2024'
    },
    {
        id: 'q8-e-tron-55-2023',
        brandId: 'audi',
        name: 'Q8 e-tron',
        trim: '55',
        range: 582,
        battery: 111,
        weightKg: 2460,
        dragCoefficient: 0.28,
        img: 'img/cars/Audi_q8_e-tron.png',
        power: '300 kW (408 HP)',
        acceleration: '5.7 s (0-100 km/h)',
        topSpeed: '210 km/h',
        batteryType: 'Li-ion',
        driveType: 'Dual Motor AWD',
        charging: '200 kW DC',
        seats: '5',
        year: '2022-2024'
    },
    {
        id: 'q8-e-tron-s-2023',
        brandId: 'audi',
        name: 'Q8 e-tron',
        trim: 'S',
        range: 530,
        battery: 111,
        weightKg: 2490,
        dragCoefficient: 0.28,
        img: 'img/cars/Audi_q8_e-tron.png',
        power: '370 kW (502 HP)',
        acceleration: '4.7 s (0-100 km/h)',
        topSpeed: '210 km/h',
        batteryType: 'Li-ion',
        driveType: 'Dual Motor AWD',
        charging: '200 kW DC',
        seats: '5',
        year: '2022-2024'
    },

    // ====== S6 e-tron ======
    {
        id: 's6-e-tron-2025',
        brandId: 'audi',
        name: 'S6 e-tron',
        trim: 'Standard',
        range: 680,
        battery: 100,
        weightKg: 2060,
        dragCoefficient: 0.24,
        img: 'img/cars/Audi_s6_e-tron.png',
        power: '430 kW (585 HP)',
        acceleration: '3.8 s (0-100 km/h)',
        topSpeed: '230 km/h',
        batteryType: 'Li-ion',
        driveType: 'Dual Motor AWD',
        charging: '270 kW DC',
        seats: '5',
        year: '2025+'
    },
    {
        id: 's6-e-tron-plus-2025',
        brandId: 'audi',
        name: 'S6 e-tron',
        trim: 'Plus',
        range: 720,
        battery: 100,
        weightKg: 2080,
        dragCoefficient: 0.24,
        img: 'img/cars/Audi_s6_e-tron.png',
        power: '430 kW (585 HP)',
        acceleration: '3.7 s (0-100 km/h)',
        topSpeed: '230 km/h',
        batteryType: 'Li-ion',
        driveType: 'Dual Motor AWD',
        charging: '270 kW DC',
        seats: '5',
        year: '2025+'
    },

];