registerCarModels([
    {
        "id": "id-3-gtx-77-2023",
        "brandId": "volkswagen",
        "name": "ID.3",
        "trim": "GTX",
        "range": 510,
        "battery": 77,
        "weightKg": 1940,
        "dragCoefficient": 0.27,
        "img": "img/cars/volkswagen/Volkswagen_ID.3.png",
        "power": "240 kW (326 HP)",
        "acceleration": "5.6 s (0-100 km/h)",
        "topSpeed": "200 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "170 kW DC",
        "seats": "5",
        "year": "2023+"
    },
    {
        "id": "id-3-pro-58-2023",
        "brandId": "volkswagen",
        "name": "ID.3",
        "trim": "Pro 58 kWh",
        "range": 430,
        "battery": 58,
        "weightKg": 1785,
        "dragCoefficient": 0.27,
        "img": "img/cars/volkswagen/Volkswagen_ID.3.png",
        "power": "150 kW (204 HP)",
        "acceleration": "7.3 s (0-100 km/h)",
        "topSpeed": "160 km/h",
        "batteryType": "Li-ion",
        "driveType": "RWD",
        "charging": "165 kW DC",
        "seats": "5",
        "year": "2023+"
    },
    {
        "id": "id-3-pro-s-77-2023",
        "brandId": "volkswagen",
        "name": "ID.3",
        "trim": "Pro S 77 kWh",
        "range": 560,
        "battery": 77,
        "weightKg": 1840,
        "dragCoefficient": 0.27,
        "img": "img/cars/volkswagen/Volkswagen_ID.3.png",
        "power": "170 kW (231 HP)",
        "acceleration": "6.9 s (0-100 km/h)",
        "topSpeed": "160 km/h",
        "batteryType": "Li-ion",
        "driveType": "RWD",
        "charging": "170 kW DC",
        "seats": "5",
        "year": "2023+"
    },
    {
        "id": "id-3-pure-52-2023",
        "brandId": "volkswagen",
        "name": "ID.3",
        "trim": "Pure",
        "range": 350,
        "battery": 52,
        "weightKg": 1720,
        "dragCoefficient": 0.27,
        "img": "img/cars/volkswagen/Volkswagen_ID.3.png",
        "power": "110 kW (150 HP)",
        "acceleration": "8.9 s (0-100 km/h)",
        "topSpeed": "160 km/h",
        "batteryType": "Li-ion",
        "driveType": "RWD",
        "charging": "145 kW DC",
        "seats": "5",
        "year": "2023+"
    },
    {
        "id": "id-3-pro-58-2020",
        "brandId": "volkswagen",
        "name": "ID.3",
        "trim": "Pro 58 kWh",
        "range": 420,
        "battery": 58,
        "weightKg": 1775,
        "dragCoefficient": 0.27,
        "img": "img/cars/volkswagen/Volkswagen_ID.3_early.png",
        "power": "150 kW (204 HP)",
        "acceleration": "7.3 s (0-100 km/h)",
        "topSpeed": "160 km/h",
        "batteryType": "Li-ion",
        "driveType": "RWD",
        "charging": "120 kW DC",
        "seats": "5",
        "year": "2020-2022"
    },
    {
        "id": "id-3-pro-s-77-2020",
        "brandId": "volkswagen",
        "name": "ID.3",
        "trim": "Pro S 77 kWh",
        "range": 540,
        "battery": 77,
        "weightKg": 1830,
        "dragCoefficient": 0.27,
        "img": "img/cars/volkswagen/Volkswagen_ID.3_early.png",
        "power": "150 kW (204 HP)",
        "acceleration": "7.9 s (0-100 km/h)",
        "topSpeed": "160 km/h",
        "batteryType": "Li-ion",
        "driveType": "RWD",
        "charging": "125 kW DC",
        "seats": "5",
        "year": "2020-2022"
    },
    {
        "id": "id-3-pure-45-2020",
        "brandId": "volkswagen",
        "name": "ID.3",
        "trim": "Pure 45 kWh",
        "range": 330,
        "battery": 45,
        "weightKg": 1710,
        "dragCoefficient": 0.27,
        "img": "img/cars/volkswagen/Volkswagen_ID.3_early.png",
        "power": "107 kW (145 HP)",
        "acceleration": "9.6 s (0-100 km/h)",
        "topSpeed": "160 km/h",
        "batteryType": "Li-ion",
        "driveType": "RWD",
        "charging": "100 kW DC",
        "seats": "5",
        "year": "2020-2022"
    }
]);
