registerCarModels([
    {
        "id": "e-tron-gt-quattro-2025",
        "brandId": "audi",
        "name": "e-tron GT",
        "trim": "quattro",
        "range": 610,
        "battery": 105,
        "weightKg": 2380,
        "dragCoefficient": 0.24,
        "img": "img/cars/audi/Audi_e-tron_GT.png",
        "power": "430 kW (585 HP)",
        "acceleration": "3.6 s (0-100 km/h)",
        "topSpeed": "245 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "320 kW DC",
        "seats": "4",
        "year": "2025+"
    },
    {
        "id": "e-tron-gt-rs-2025",
        "brandId": "audi",
        "name": "e-tron GT",
        "trim": "RS",
        "range": 575,
        "battery": 105,
        "weightKg": 2425,
        "dragCoefficient": 0.24,
        "img": "img/cars/audi/Audi_e-tron_GT.png",
        "power": "500 kW (680 HP)",
        "acceleration": "3.1 s (0-100 km/h)",
        "topSpeed": "250 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "320 kW DC",
        "seats": "4",
        "year": "2025+"
    },
    {
        "id": "e-tron-gt-rs-performance-2025",
        "brandId": "audi",
        "name": "e-tron GT",
        "trim": "RS Performance",
        "range": 560,
        "battery": 105,
        "weightKg": 2460,
        "dragCoefficient": 0.24,
        "img": "img/cars/audi/Audi_e-tron_GT.png",
        "power": "560 kW (761 HP)",
        "acceleration": "2.8 s (0-100 km/h)",
        "topSpeed": "250 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "320 kW DC",
        "seats": "4",
        "year": "2025+"
    },
    {
        "id": "e-tron-gt-s-2025",
        "brandId": "audi",
        "name": "e-tron GT",
        "trim": "S",
        "range": 595,
        "battery": 105,
        "weightKg": 2405,
        "dragCoefficient": 0.24,
        "img": "img/cars/audi/Audi_e-tron_GT.png",
        "power": "500 kW (680 HP)",
        "acceleration": "3.4 s (0-100 km/h)",
        "topSpeed": "245 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "320 kW DC",
        "seats": "4",
        "year": "2025+"
    },
    {
        "id": "e-tron-gt-quattro-2021",
        "brandId": "audi",
        "name": "e-tron GT",
        "trim": "Quattro",
        "range": 488,
        "battery": 96,
        "weightKg": 2350,
        "dragCoefficient": 0.24,
        "img": "img/cars/audi/Audi_e-tron_GT.png",
        "power": "350 kW (476 HP)",
        "acceleration": "4.1 s (0-100 km/h)",
        "topSpeed": "245 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "270 kW DC",
        "seats": "4",
        "year": "2021-2024"
    },
    {
        "id": "e-tron-gt-rs-2021",
        "brandId": "audi",
        "name": "e-tron GT",
        "trim": "RS",
        "range": 472,
        "battery": 96,
        "weightKg": 2395,
        "dragCoefficient": 0.24,
        "img": "img/cars/audi/Audi_e-tron_GT.png",
        "power": "440 kW (598 HP)",
        "acceleration": "3.3 s (0-100 km/h)",
        "topSpeed": "250 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "270 kW DC",
        "seats": "4",
        "year": "2021-2024"
    }
]);
