registerCarModels([
    {
        "id": "r1s-2021",
        "brandId": "rivian",
        "name": "R1S",
        "trim": "Standard Pack",
        "range": 384,
        "battery": 108,
        "weightKg": 2600,
        "dragCoefficient": 0.29,
        "img": "img/cars/rivian/Rivian_R1S.png",
        "power": "Dual Motor AWD",
        "acceleration": "5.5 s (0-100 km/h)",
        "topSpeed": "200 km/h",
        "batteryType": "Li-ion",
        "driveType": "AWD",
        "charging": "200 kW DC",
        "seats": "7",
        "year": "2021-2024"
    },
    {
        "id": "r1s-2021-large-quad",
        "brandId": "rivian",
        "name": "R1S",
        "trim": "Large Pack (Quad Motor)",
        "range": 463,
        "battery": 130,
        "weightKg": 2650,
        "dragCoefficient": 0.29,
        "img": "img/cars/rivian/Rivian_R1S.png",
        "power": "Quad Motor AWD",
        "acceleration": "3.9 s (0-100 km/h)",
        "topSpeed": "240 km/h",
        "batteryType": "Li-ion",
        "driveType": "AWD",
        "charging": "250 kW DC",
        "seats": "7",
        "year": "2021-2024"
    },
    {
        "id": "r1s-2021-large-dual",
        "brandId": "rivian",
        "name": "R1S",
        "trim": "Large Pack (Dual Motor)",
        "range": 463,
        "battery": 130,
        "weightKg": 2620,
        "dragCoefficient": 0.29,
        "img": "img/cars/rivian/Rivian_R1S.png",
        "power": "Dual Motor AWD",
        "acceleration": "4.3 s (0-100 km/h)",
        "topSpeed": "230 km/h",
        "batteryType": "Li-ion",
        "driveType": "AWD",
        "charging": "250 kW DC",
        "seats": "7",
        "year": "2021-2024"
    },
    {
        "id": "r1s-2021-large-performance",
        "brandId": "rivian",
        "name": "R1S",
        "trim": "Large Pack Performance",
        "range": 450,
        "battery": 130,
        "weightKg": 2630,
        "dragCoefficient": 0.29,
        "img": "img/cars/rivian/Rivian_R1S.png",
        "power": "Dual Motor AWD",
        "acceleration": "3.8 s (0-100 km/h)",
        "topSpeed": "245 km/h",
        "batteryType": "Li-ion",
        "driveType": "AWD",
        "charging": "250 kW DC",
        "seats": "7",
        "year": "2021-2024"
    },
    {
        "id": "r1s-2021-max",
        "brandId": "rivian",
        "name": "R1S",
        "trim": "Max Pack",
        "range": 514,
        "battery": 144.5,
        "weightKg": 2750,
        "dragCoefficient": 0.29,
        "img": "img/cars/rivian/Rivian_R1S.png",
        "power": "Dual Motor AWD",
        "acceleration": "3.5 s (0-100 km/h)",
        "topSpeed": "250 km/h",
        "batteryType": "Li-ion",
        "driveType": "AWD",
        "charging": "300 kW DC",
        "seats": "7",
        "year": "2021-2024"
    },
    {
        "id": "r1s-2021-max-performance",
        "brandId": "rivian",
        "name": "R1S",
        "trim": "Max Pack Performance",
        "range": 510,
        "battery": 144.5,
        "weightKg": 2760,
        "dragCoefficient": 0.29,
        "img": "img/cars/rivian/Rivian_R1S.png",
        "power": "Dual Motor AWD",
        "acceleration": "3.3 s (0-100 km/h)",
        "topSpeed": "260 km/h",
        "batteryType": "Li-ion",
        "driveType": "AWD",
        "charging": "300 kW DC",
        "seats": "7",
        "year": "2021-2024"
    },
    {
        "id": "r1s-2021-standard-plus",
        "brandId": "rivian",
        "name": "R1S",
        "trim": "Standard+ Pack",
        "range": 424,
        "battery": 119,
        "weightKg": 2610,
        "dragCoefficient": 0.29,
        "img": "img/cars/rivian/Rivian_R1S.png",
        "power": "Dual Motor AWD",
        "acceleration": "4.9 s (0-100 km/h)",
        "topSpeed": "210 km/h",
        "batteryType": "Li-ion",
        "driveType": "AWD",
        "charging": "250 kW DC",
        "seats": "7",
        "year": "2021-2024"
    },
    {
        "id": "r1s-2025-large",
        "brandId": "rivian",
        "name": "R1S",
        "trim": "Large Pack",
        "range": 395,
        "battery": 111,
        "weightKg": 2660,
        "dragCoefficient": 0.29,
        "img": "img/cars/rivian/Rivian_R1S.png",
        "power": "Dual Motor AWD",
        "acceleration": "4.2 s (0-100 km/h)",
        "topSpeed": "230 km/h",
        "batteryType": "Li-ion",
        "driveType": "AWD",
        "charging": "250 kW DC",
        "seats": "7",
        "year": "2025+"
    },
    {
        "id": "r1s-2025-large-plus",
        "brandId": "rivian",
        "name": "R1S",
        "trim": "Large+ Pack",
        "range": 424,
        "battery": 119,
        "weightKg": 2670,
        "dragCoefficient": 0.29,
        "img": "img/cars/rivian/Rivian_R1S.png",
        "power": "Dual Motor AWD",
        "acceleration": "4.0 s (0-100 km/h)",
        "topSpeed": "235 km/h",
        "batteryType": "Li-ion",
        "driveType": "AWD",
        "charging": "250 kW DC",
        "seats": "7",
        "year": "2025+"
    },
    {
        "id": "r1s-2025-max-tri",
        "brandId": "rivian",
        "name": "R1S",
        "trim": "Max Pack (Tri Motor)",
        "range": 514,
        "battery": 144.5,
        "weightKg": 2780,
        "dragCoefficient": 0.29,
        "img": "img/cars/rivian/Rivian_R1S.png",
        "power": "Tri Motor AWD",
        "acceleration": "3.2 s (0-100 km/h)",
        "topSpeed": "265 km/h",
        "batteryType": "Li-ion",
        "driveType": "AWD",
        "charging": "300 kW DC",
        "seats": "7",
        "year": "2025+"
    },
    {
        "id": "r1s-2025-max-quad",
        "brandId": "rivian",
        "name": "R1S",
        "trim": "Max Pack (Quad Motor)",
        "range": 514,
        "battery": 144.5,
        "weightKg": 2800,
        "dragCoefficient": 0.29,
        "img": "img/cars/rivian/Rivian_R1S.png",
        "power": "Quad Motor AWD",
        "acceleration": "3.1 s (0-100 km/h)",
        "topSpeed": "270 km/h",
        "batteryType": "Li-ion",
        "driveType": "AWD",
        "charging": "300 kW DC",
        "seats": "7",
        "year": "2025+"
    },
    {
        "id": "r1s-2025-max-dual",
        "brandId": "rivian",
        "name": "R1S",
        "trim": "Max Pack (Dual Motor)",
        "range": 514,
        "battery": 144.5,
        "weightKg": 2770,
        "dragCoefficient": 0.29,
        "img": "img/cars/rivian/Rivian_R1S.png",
        "power": "Dual Motor AWD",
        "acceleration": "3.4 s (0-100 km/h)",
        "topSpeed": "260 km/h",
        "batteryType": "Li-ion",
        "driveType": "AWD",
        "charging": "300 kW DC",
        "seats": "7",
        "year": "2025+"
    },
    {
        "id": "r1s-2025-standard",
        "brandId": "rivian",
        "name": "R1S",
        "trim": "Standard Pack",
        "range": 351,
        "battery": 98.7,
        "weightKg": 2590,
        "dragCoefficient": 0.29,
        "img": "img/cars/rivian/Rivian_R1S.png",
        "power": "Dual Motor AWD",
        "acceleration": "6.0 s (0-100 km/h)",
        "topSpeed": "200 km/h",
        "batteryType": "Li-ion",
        "driveType": "AWD",
        "charging": "200 kW DC",
        "seats": "7",
        "year": "2025+"
    }
]);
