registerCarModels([
    {
        "id": "e-tron-50-2023",
        "brandId": "audi",
        "name": "e-tron",
        "trim": "50",
        "range": 450,
        "battery": 83,
        "weightKg": 2240,
        "dragCoefficient": 0.27,
        "img": "img/cars/audi/Audi_e-tron_s.png",
        "power": "170 kW (230 HP)",
        "acceleration": "8.4 s (0-100 km/h)",
        "topSpeed": "200 km/h",
        "batteryType": "Li-ion",
        "driveType": "RWD",
        "charging": "150 kW DC",
        "seats": "5",
        "year": "2019-2024"
    },
    {
        "id": "e-tron-55-2023",
        "brandId": "audi",
        "name": "e-tron",
        "trim": "55",
        "range": 530,
        "battery": 100,
        "weightKg": 2360,
        "dragCoefficient": 0.27,
        "img": "img/cars/audi/Audi_e-tron_s.png",
        "power": "230 kW (313 HP)",
        "acceleration": "6.3 s (0-100 km/h)",
        "topSpeed": "200 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "150 kW DC",
        "seats": "5",
        "year": "2019-2024"
    },
    {
        "id": "e-tron-s-2023",
        "brandId": "audi",
        "name": "e-tron",
        "trim": "S",
        "range": 490,
        "battery": 100,
        "weightKg": 2380,
        "dragCoefficient": 0.27,
        "img": "img/cars/audi/Audi_e-tron_s.png",
        "power": "370 kW (502 HP)",
        "acceleration": "4.3 s (0-100 km/h)",
        "topSpeed": "210 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "150 kW DC",
        "seats": "5",
        "year": "2019-2024"
    }
]);
