registerCarModels([
    {
        "id": "cybertruck-awd-2024",
        "brandId": "tesla",
        "name": "Cybertruck",
        "trim": "All-Wheel Drive",
        "range": 547,
        "battery": 129,
        "weightKg": 3009,
        "dragCoefficient": 0.34,
        "img": "img/cars/tesla/Tesla_Cybertruck.png",
        "power": "447 kW (608 HP)",
        "acceleration": "4.1 s (0-100 km/h)",
        "topSpeed": "180 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "250 kW DC",
        "seats": "5",
        "year": "2024+"
    },
    {
        "id": "cybertruck-awd-range-extender-2024",
        "brandId": "tesla",
        "name": "Cybertruck",
        "trim": "All-Wheel Drive Range Extender",
        "range": 756,
        "battery": 178,
        "weightKg": 3150,
        "dragCoefficient": 0.34,
        "img": "img/cars/tesla/Tesla_Cybertruck.png",
        "power": "447 kW (608 HP)",
        "acceleration": "4.1 s (0-100 km/h)",
        "topSpeed": "180 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "250 kW DC",
        "seats": "5",
        "year": "2024+"
    },
    {
        "id": "cybertruck-cyberbeast-2024",
        "brandId": "tesla",
        "name": "Cybertruck",
        "trim": "Cyberbeast",
        "range": 515,
        "battery": 129,
        "weightKg": 3113,
        "dragCoefficient": 0.34,
        "img": "img/cars/tesla/Tesla_Cybertruck.png",
        "power": "630 kW (857 HP)",
        "acceleration": "2.7 s (0-100 km/h)",
        "topSpeed": "210 km/h",
        "batteryType": "Li-ion",
        "driveType": "Tri Motor AWD",
        "charging": "250 kW DC",
        "seats": "5",
        "year": "2024+",
        "isEstimate": true
    },
    {
        "id": "cybertruck-cyberbeast-range-extender-2024",
        "brandId": "tesla",
        "name": "Cybertruck",
        "trim": "Cyberbeast Range Extender",
        "range": 708,
        "battery": 178,
        "weightKg": 3250,
        "dragCoefficient": 0.34,
        "img": "img/cars/tesla/Tesla_Cybertruck.png",
        "power": "630 kW (857 HP)",
        "acceleration": "2.7 s (0-100 km/h)",
        "topSpeed": "210 km/h",
        "batteryType": "Li-ion",
        "driveType": "Tri Motor AWD",
        "charging": "250 kW DC",
        "seats": "5",
        "year": "2024+",
        "isEstimate": true
    },
    {
        "id": "cybertruck-rwd-2024",
        "brandId": "tesla",
        "name": "Cybertruck",
        "trim": "Rear-Wheel Drive",
        "range": 402,
        "battery": 93,
        "weightKg": 2840,
        "dragCoefficient": 0.34,
        "img": "img/cars/tesla/Tesla_Cybertruck.png",
        "power": "235 kW (320 HP)",
        "acceleration": "6.7 s (0-100 km/h)",
        "topSpeed": "180 km/h",
        "batteryType": "Li-ion",
        "driveType": "RWD",
        "charging": "250 kW DC",
        "seats": "5",
        "year": "2024+",
        "isEstimate": true
    }
]);
