registerCarModels([
    {
        "id": "zoe-ze40-r110-ccs-2020",
        "brandId": "renault",
        "name": "Zoe",
        "trim": "Z.E. 40 R110 with CCS",
        "range": 320,
        "battery": 40,
        "weightKg": 1450,
        "dragCoefficient": 0.29,
        "img": "img/cars/renault/Renault_zoe_e-tech.png",
        "power": "80 kW (108 HP)",
        "acceleration": "11.4 s (0-100 km/h)",
        "topSpeed": "135 km/h",
        "batteryType": "Li-ion",
        "driveType": "FWD",
        "charging": "50 kW DC",
        "seats": "5",
        "year": "2020+"
    },
    {
        "id": "zoe-ze40-r110-no-ccs-2020",
        "brandId": "renault",
        "name": "Zoe",
        "trim": "Z.E. 40 R110 without CCS",
        "range": 320,
        "battery": 40,
        "weightKg": 1450,
        "dragCoefficient": 0.29,
        "img": "img/cars/renault/Renault_zoe_e-tech.png",
        "power": "80 kW (108 HP)",
        "acceleration": "11.4 s (0-100 km/h)",
        "topSpeed": "135 km/h",
        "batteryType": "Li-ion",
        "driveType": "FWD",
        "charging": "22 kW AC",
        "seats": "5",
        "year": "2020+"
    },
    {
        "id": "zoe-ze50-r110-ccs-2020",
        "brandId": "renault",
        "name": "Zoe",
        "trim": "Z.E. 50 R110 with CCS",
        "range": 390,
        "battery": 52,
        "weightKg": 1502,
        "dragCoefficient": 0.29,
        "img": "img/cars/renault/Renault_zoe_e-tech.png",
        "power": "80 kW (108 HP)",
        "acceleration": "11.4 s (0-100 km/h)",
        "topSpeed": "135 km/h",
        "batteryType": "Li-ion",
        "driveType": "FWD",
        "charging": "50 kW DC",
        "seats": "5",
        "year": "2020+"
    },
    {
        "id": "zoe-ze50-r110-no-ccs-2020",
        "brandId": "renault",
        "name": "Zoe",
        "trim": "Z.E. 50 R110 without CCS",
        "range": 390,
        "battery": 52,
        "weightKg": 1502,
        "dragCoefficient": 0.29,
        "img": "img/cars/renault/Renault_zoe_e-tech.png",
        "power": "80 kW (108 HP)",
        "acceleration": "11.4 s (0-100 km/h)",
        "topSpeed": "135 km/h",
        "batteryType": "Li-ion",
        "driveType": "FWD",
        "charging": "22 kW AC",
        "seats": "5",
        "year": "2020+"
    },
    {
        "id": "zoe-ze50-r135-ccs-2020",
        "brandId": "renault",
        "name": "Zoe",
        "trim": "Z.E. 50 R135 with CCS",
        "range": 395,
        "battery": 52,
        "weightKg": 1502,
        "dragCoefficient": 0.29,
        "img": "img/cars/renault/Renault_zoe_e-tech.png",
        "power": "100 kW (136 HP)",
        "acceleration": "9.5 s (0-100 km/h)",
        "topSpeed": "140 km/h",
        "batteryType": "Li-ion",
        "driveType": "FWD",
        "charging": "50 kW DC",
        "seats": "5",
        "year": "2020+"
    },
    {
        "id": "zoe-ze50-r135-no-ccs-2020",
        "brandId": "renault",
        "name": "Zoe",
        "trim": "Z.E. 50 R135 without CCS",
        "range": 395,
        "battery": 52,
        "weightKg": 1502,
        "dragCoefficient": 0.29,
        "img": "img/cars/renault/Renault_zoe_e-tech.png",
        "power": "100 kW (136 HP)",
        "acceleration": "9.5 s (0-100 km/h)",
        "topSpeed": "140 km/h",
        "batteryType": "Li-ion",
        "driveType": "FWD",
        "charging": "22 kW AC",
        "seats": "5",
        "year": "2020+"
    },
    {
        "id": "zoe-22-q210-2013",
        "brandId": "renault",
        "name": "Zoe",
        "trim": "22 kWh Q210",
        "range": 150,
        "battery": 22,
        "weightKg": 1400,
        "dragCoefficient": 0.29,
        "img": "img/cars/renault/Renault_zoe_e-tech_early.png",
        "power": "65 kW (88 HP)",
        "acceleration": "13.5 s (0-100 km/h)",
        "topSpeed": "135 km/h",
        "batteryType": "Li-ion",
        "driveType": "FWD",
        "charging": "43 kW AC",
        "seats": "5",
        "year": "2013-2019"
    },
    {
        "id": "zoe-22-r240-2013",
        "brandId": "renault",
        "name": "Zoe",
        "trim": "22 kWh R240",
        "range": 160,
        "battery": 22,
        "weightKg": 1400,
        "dragCoefficient": 0.29,
        "img": "img/cars/renault/Renault_zoe_e-tech_early.png",
        "power": "65 kW (88 HP)",
        "acceleration": "13.5 s (0-100 km/h)",
        "topSpeed": "135 km/h",
        "batteryType": "Li-ion",
        "driveType": "FWD",
        "charging": "22 kW AC",
        "seats": "5",
        "year": "2013-2019"
    },
    {
        "id": "zoe-ze40-q90-2013",
        "brandId": "renault",
        "name": "Zoe",
        "trim": "Z.E. 40 Q90",
        "range": 300,
        "battery": 40,
        "weightKg": 1450,
        "dragCoefficient": 0.29,
        "img": "img/cars/renault/Renault_zoe_e-tech_early.png",
        "power": "65 kW (88 HP)",
        "acceleration": "13.0 s (0-100 km/h)",
        "topSpeed": "135 km/h",
        "batteryType": "Li-ion",
        "driveType": "FWD",
        "charging": "43 kW AC",
        "seats": "5",
        "year": "2013-2019"
    },
    {
        "id": "zoe-ze40-r110-2013",
        "brandId": "renault",
        "name": "Zoe",
        "trim": "Z.E. 40 R110",
        "range": 320,
        "battery": 40,
        "weightKg": 1450,
        "dragCoefficient": 0.29,
        "img": "img/cars/renault/Renault_zoe_e-tech_early.png",
        "power": "80 kW (108 HP)",
        "acceleration": "11.4 s (0-100 km/h)",
        "topSpeed": "135 km/h",
        "batteryType": "Li-ion",
        "driveType": "FWD",
        "charging": "22 kW AC",
        "seats": "5",
        "year": "2013-2019"
    },
    {
        "id": "zoe-ze40-r90-2013",
        "brandId": "renault",
        "name": "Zoe",
        "trim": "Z.E. 40 R90",
        "range": 300,
        "battery": 40,
        "weightKg": 1450,
        "dragCoefficient": 0.29,
        "img": "img/cars/renault/Renault_zoe_e-tech_early.png",
        "power": "68 kW (92 HP)",
        "acceleration": "12.2 s (0-100 km/h)",
        "topSpeed": "135 km/h",
        "batteryType": "Li-ion",
        "driveType": "FWD",
        "charging": "22 kW AC",
        "seats": "5",
        "year": "2013-2019"
    }
]);
