registerCarModels([
    {
        "id": "a6-e-tron-40-2024",
        "brandId": "audi",
        "name": "A6 e-tron",
        "trim": "40",
        "range": 720,
        "battery": 83,
        "weightKg": 1795,
        "dragCoefficient": 0.24,
        "img": "img/cars/audi/Audi_a6_e-tron.png",
        "power": "160 kW (218 HP)",
        "acceleration": "8.5 s (0-100 km/h)",
        "topSpeed": "200 km/h",
        "batteryType": "Li-ion",
        "driveType": "RWD",
        "charging": "180 kW DC",
        "seats": "5",
        "year": "2024+"
    },
    {
        "id": "a6-e-tron-55-2024",
        "brandId": "audi",
        "name": "A6 e-tron",
        "trim": "55",
        "range": 750,
        "battery": 100,
        "weightKg": 1850,
        "dragCoefficient": 0.24,
        "img": "img/cars/audi/Audi_a6_e-tron.png",
        "power": "270 kW (367 HP)",
        "acceleration": "5.4 s (0-100 km/h)",
        "topSpeed": "210 km/h",
        "batteryType": "Li-ion",
        "driveType": "RWD",
        "charging": "270 kW DC",
        "seats": "5",
        "year": "2024+"
    },
    {
        "id": "a6-e-tron-55-quattro-2024",
        "brandId": "audi",
        "name": "A6 e-tron",
        "trim": "55 quattro",
        "range": 700,
        "battery": 100,
        "weightKg": 1950,
        "dragCoefficient": 0.24,
        "img": "img/cars/audi/Audi_a6_e-tron.png",
        "power": "340 kW (462 HP)",
        "acceleration": "4.5 s (0-100 km/h)",
        "topSpeed": "210 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "270 kW DC",
        "seats": "5",
        "year": "2024+"
    }
]);
