registerCarModels([
    {
        "id": "model-x-75d-2016",
        "brandId": "tesla",
        "name": "Model X",
        "trim": "75D",
        "range": 417,
        "battery": 75,
        "weightKg": 2468,
        "dragCoefficient": 0.24,
        "img": "img/cars/tesla/Tesla_Model_X_early.png",
        "power": "386 kW (525 HP)",
        "acceleration": "5.2 s (0-100 km/h)",
        "topSpeed": "210 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "120 kW DC",
        "seats": "7",
        "year": "2015-2018"
    },
    {
        "id": "model-x-90d-2016",
        "brandId": "tesla",
        "name": "Model X",
        "trim": "90D",
        "range": 489,
        "battery": 90,
        "weightKg": 2490,
        "dragCoefficient": 0.24,
        "img": "img/cars/tesla/Tesla_Model_X_early.png",
        "power": "386 kW (525 HP)",
        "acceleration": "4.8 s (0-100 km/h)",
        "topSpeed": "250 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "120 kW DC",
        "seats": "7",
        "year": "2015-2018"
    },
    {
        "id": "model-x-p90d-2016",
        "brandId": "tesla",
        "name": "Model X",
        "trim": "P90D",
        "range": 467,
        "battery": 90,
        "weightKg": 2507,
        "dragCoefficient": 0.24,
        "img": "img/cars/tesla/Tesla_Model_X_early.png",
        "power": "568 kW (773 HP)",
        "acceleration": "3.8 s (0-100 km/h)",
        "topSpeed": "250 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "120 kW DC",
        "seats": "7",
        "year": "2015-2018"
    },
    {
        "id": "model-x-100d-2017",
        "brandId": "tesla",
        "name": "Model X",
        "trim": "100D",
        "range": 565,
        "battery": 98,
        "weightKg": 2518,
        "dragCoefficient": 0.24,
        "img": "img/cars/tesla/Tesla_Model_X_early.png",
        "power": "386 kW (525 HP)",
        "acceleration": "4.9 s (0-100 km/h)",
        "topSpeed": "250 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "120 kW DC",
        "seats": "7",
        "year": "2015-2018"
    },
    {
        "id": "model-x-p100d-2017",
        "brandId": "tesla",
        "name": "Model X",
        "trim": "P100D",
        "range": 542,
        "battery": 98,
        "weightKg": 2560,
        "dragCoefficient": 0.24,
        "img": "img/cars/tesla/Tesla_Model_X_early.png",
        "power": "588 kW (800 HP)",
        "acceleration": "3.1 s (0-100 km/h)",
        "topSpeed": "250 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "120 kW DC",
        "seats": "7",
        "year": "2015-2018"
    },
    {
        "id": "model-x-raven-long-range-2019",
        "brandId": "tesla",
        "name": "Model X",
        "trim": "Range Upgrade (Raven) Long Range",
        "range": 565,
        "battery": 98,
        "weightKg": 2487,
        "dragCoefficient": 0.24,
        "img": "img/cars/tesla/Tesla_Model_X_early.png",
        "power": "386 kW (525 HP)",
        "acceleration": "4.8 s (0-100 km/h)",
        "topSpeed": "250 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "150 kW DC",
        "seats": "7",
        "year": "2019"
    },
    {
        "id": "model-x-raven-performance-2019",
        "brandId": "tesla",
        "name": "Model X",
        "trim": "Range Upgrade (Raven) Performance",
        "range": 507,
        "battery": 98,
        "weightKg": 2510,
        "dragCoefficient": 0.24,
        "img": "img/cars/tesla/Tesla_Model_X_early.png",
        "power": "562 kW (765 HP)",
        "acceleration": "3.5 s (0-100 km/h)",
        "topSpeed": "262 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "150 kW DC",
        "seats": "7",
        "year": "2019"
    },
    {
        "id": "model-x-long-range-plus-2020",
        "brandId": "tesla",
        "name": "Model X",
        "trim": "Long Range Plus",
        "range": 580,
        "battery": 98,
        "weightKg": 2489,
        "dragCoefficient": 0.24,
        "img": "img/cars/tesla/Tesla_Model_X_facelift.png",
        "power": "386 kW (525 HP)",
        "acceleration": "4.6 s (0-100 km/h)",
        "topSpeed": "250 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "200 kW DC",
        "seats": "7",
        "year": "2020"
    },
    {
        "id": "model-x-performance-2020",
        "brandId": "tesla",
        "name": "Model X",
        "trim": "Performance",
        "range": 548,
        "battery": 98,
        "weightKg": 2514,
        "dragCoefficient": 0.24,
        "img": "img/cars/tesla/Tesla_Model_X_facelift.png",
        "power": "562 kW (765 HP)",
        "acceleration": "3.7 s (0-100 km/h)",
        "topSpeed": "262 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "200 kW DC",
        "seats": "7",
        "year": "2020"
    },
    {
        "id": "model-x-long-range-2021",
        "brandId": "tesla",
        "name": "Model X",
        "trim": "Facelift Long Range",
        "range": 576,
        "battery": 100,
        "weightKg": 2352,
        "dragCoefficient": 0.24,
        "img": "img/cars/tesla/Tesla_Model_X_facelift.png",
        "power": "500 kW (670 HP)",
        "acceleration": "3.9 s (0-100 km/h)",
        "topSpeed": "250 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "250 kW DC",
        "seats": "7",
        "year": "2021+"
    },
    {
        "id": "model-x-plaid-2021",
        "brandId": "tesla",
        "name": "Model X",
        "trim": "Plaid",
        "range": 543,
        "battery": 100,
        "weightKg": 2485,
        "dragCoefficient": 0.24,
        "img": "img/cars/tesla/Tesla_Model_X_facelift.png",
        "power": "760 kW (1020 HP)",
        "acceleration": "2.6 s (0-100 km/h)",
        "topSpeed": "262 km/h",
        "batteryType": "Li-ion",
        "driveType": "Tri Motor AWD",
        "charging": "250 kW DC",
        "seats": "6",
        "year": "2021+"
    }
]);
