registerCarModels([
    {
        "id": "id-6-pro-2024",
        "brandId": "volkswagen",
        "name": "ID.6",
        "trim": "Pro",
        "range": 520,
        "battery": 84.8,
        "weightKg": 2300,
        "dragCoefficient": 0.28,
        "img": "img/cars/volkswagen/Volkswagen_ID.6.png",
        "power": "230 kW (313 HP)",
        "acceleration": "7.1 s (0-100 km/h)",
        "topSpeed": "160 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "170 kW DC",
        "seats": "7",
        "year": "2024+"
    },
    {
        "id": "id-6-pro-77-2022",
        "brandId": "volkswagen",
        "name": "ID.6",
        "trim": "Pro",
        "range": 430,
        "battery": 77,
        "weightKg": 2230,
        "dragCoefficient": 0.28,
        "img": "img/cars/volkswagen/Volkswagen_ID.6.png",
        "power": "150 kW (204 HP)",
        "acceleration": "9.3 s (0-100 km/h)",
        "topSpeed": "160 km/h",
        "batteryType": "Li-ion",
        "driveType": "RWD",
        "charging": "125 kW DC",
        "seats": "7",
        "year": "2022"
    },
    {
        "id": "id-6-pro-4motion-77-2022",
        "brandId": "volkswagen",
        "name": "ID.6",
        "trim": "Pro 4MOTION",
        "range": 410,
        "battery": 77,
        "weightKg": 2340,
        "dragCoefficient": 0.28,
        "img": "img/cars/volkswagen/Volkswagen_ID.6.png",
        "power": "230 kW (313 HP)",
        "acceleration": "6.7 s (0-100 km/h)",
        "topSpeed": "160 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "125 kW DC",
        "seats": "7",
        "year": "2022"
    }
]);
