registerCarModels([
    {
        "id": "megane-e-tech-ev40-2026",
        "brandId": "renault",
        "name": "Megane E-Tech",
        "trim": "EV40",
        "range": 320,
        "battery": 40,
        "weightKg": 1620,
        "dragCoefficient": 0.29,
        "img": "img/cars/renault/Renault_megane_e-tech.png",
        "power": "96 kW (130 HP)",
        "acceleration": "10.0 s (0-100 km/h)",
        "topSpeed": "150 km/h",
        "batteryType": "Li-ion",
        "driveType": "FWD",
        "charging": "85 kW DC",
        "seats": "5",
        "year": "2026"
    },
    {
        "id": "megane-e-tech-ev60-2026",
        "brandId": "renault",
        "name": "Megane E-Tech",
        "trim": "EV60",
        "range": 480,
        "battery": 60,
        "weightKg": 1700,
        "dragCoefficient": 0.29,
        "img": "img/cars/renault/Renault_megane_e-tech.png",
        "power": "160 kW (218 HP)",
        "acceleration": "7.4 s (0-100 km/h)",
        "topSpeed": "160 km/h",
        "batteryType": "Li-ion",
        "driveType": "FWD",
        "charging": "130 kW DC",
        "seats": "5",
        "year": "2026"
    },
    {
        "id": "megane-e-tech-ev40-2022-2025",
        "brandId": "renault",
        "name": "Megane E-Tech",
        "trim": "EV40",
        "range": 300,
        "battery": 40,
        "weightKg": 1610,
        "dragCoefficient": 0.29,
        "img": "img/cars/renault/Renault_megane_e-tech.png",
        "power": "96 kW (130 HP)",
        "acceleration": "10.0 s (0-100 km/h)",
        "topSpeed": "150 km/h",
        "batteryType": "Li-ion",
        "driveType": "FWD",
        "charging": "85 kW DC",
        "seats": "5",
        "year": "2022-2025"
    },
    {
        "id": "megane-e-tech-ev60-2022-2025",
        "brandId": "renault",
        "name": "Megane E-Tech",
        "trim": "EV60",
        "range": 470,
        "battery": 60,
        "weightKg": 1700,
        "dragCoefficient": 0.29,
        "img": "img/cars/renault/Renault_megane_e-tech.png",
        "power": "160 kW (218 HP)",
        "acceleration": "7.4 s (0-100 km/h)",
        "topSpeed": "160 km/h",
        "batteryType": "Li-ion",
        "driveType": "FWD",
        "charging": "130 kW DC",
        "seats": "5",
        "year": "2022-2025"
    }
]);
