registerCarModels([
    {
        "id": "ix-xdrive40-2022",
        "brandId": "bmw",
        "name": "iX",
        "trim": "xDrive40",
        "range": 425,
        "battery": 71,
        "weightKg": 2440,
        "dragCoefficient": 0.25,
        "img": "img/cars/bmw/BMW_iX.png",
        "power": "240 kW (326 HP)",
        "acceleration": "6.1 s (0-100 km/h)",
        "topSpeed": "200 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "150 kW DC",
        "seats": "5",
        "year": "2022-2024"
    },
    {
        "id": "ix-xdrive50-2022",
        "brandId": "bmw",
        "name": "iX",
        "trim": "xDrive50",
        "range": 630,
        "battery": 105.2,
        "weightKg": 2585,
        "dragCoefficient": 0.25,
        "img": "img/cars/bmw/BMW_iX.png",
        "power": "385 kW (523 HP)",
        "acceleration": "4.6 s (0-100 km/h)",
        "topSpeed": "250 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "200 kW DC",
        "seats": "5",
        "year": "2022-2024"
    },
    {
        "id": "ix-m60-2022",
        "brandId": "bmw",
        "name": "iX",
        "trim": "M60 xDrive",
        "range": 566,
        "battery": 105.2,
        "weightKg": 2659,
        "dragCoefficient": 0.25,
        "img": "img/cars/bmw/BMW_iX.png",
        "power": "455 kW (619 HP)",
        "acceleration": "3.8 s (0-100 km/h)",
        "topSpeed": "250 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "200 kW DC",
        "seats": "5",
        "year": "2022-2024"
    },
    {
        "id": "ix-xdrive45-2025",
        "brandId": "bmw",
        "name": "iX",
        "trim": "xDrive45",
        "range": 502,
        "battery": 94.8,
        "weightKg": 2525,
        "dragCoefficient": 0.25,
        "img": "img/cars/bmw/BMW_iX.png",
        "power": "300 kW (408 HP)",
        "acceleration": "4.9 s (0-100 km/h)",
        "topSpeed": "200 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "175 kW DC",
        "seats": "5",
        "year": "2025+"
    },
    {
        "id": "ix-xdrive60-2025",
        "brandId": "bmw",
        "name": "iX",
        "trim": "xDrive60",
        "range": 700,
        "battery": 109.2,
        "weightKg": 2582,
        "dragCoefficient": 0.25,
        "img": "img/cars/bmw/BMW_iX.png",
        "power": "400 kW (544 HP)",
        "acceleration": "4.4 s (0-100 km/h)",
        "topSpeed": "250 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "195 kW DC",
        "seats": "5",
        "year": "2025+"
    },
    {
        "id": "ix-m70-2025",
        "brandId": "bmw",
        "name": "iX",
        "trim": "M70 xDrive",
        "range": 600,
        "battery": 109.2,
        "weightKg": 2653,
        "dragCoefficient": 0.25,
        "img": "img/cars/bmw/BMW_iX_M70.png",
        "power": "485 kW (660 HP)",
        "acceleration": "3.6 s (0-100 km/h)",
        "topSpeed": "250 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "195 kW DC",
        "seats": "5",
        "year": "2025+"
    }
]);
