registerCarModels([
    {
        "id": "i7-edrive50-2023",
        "brandId": "bmw",
        "name": "i7",
        "trim": "eDrive50",
        "range": 611,
        "battery": 101.7,
        "weightKg": 2595,
        "dragCoefficient": 0.24,
        "img": "img/cars/bmw/BMW_i7.png",
        "power": "335 kW (455 HP)",
        "acceleration": "5.5 s (0-100 km/h)",
        "topSpeed": "205 km/h",
        "batteryType": "Li-ion",
        "driveType": "RWD",
        "charging": "200 kW DC",
        "seats": "5",
        "year": "2023+"
    },
    {
        "id": "i7-xdrive60-2023",
        "brandId": "bmw",
        "name": "i7",
        "trim": "xDrive60",
        "range": 625,
        "battery": 101.7,
        "weightKg": 2640,
        "dragCoefficient": 0.24,
        "img": "img/cars/bmw/BMW_i7.png",
        "power": "400 kW (544 HP)",
        "acceleration": "4.7 s (0-100 km/h)",
        "topSpeed": "240 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "200 kW DC",
        "seats": "5",
        "year": "2023+"
    },
    {
        "id": "i7-m70-xdrive-2024",
        "brandId": "bmw",
        "name": "i7",
        "trim": "M70 xDrive",
        "range": 560,
        "battery": 101.7,
        "weightKg": 2695,
        "dragCoefficient": 0.24,
        "img": "img/cars/bmw/BMW_i7.png",
        "power": "485 kW (660 HP)",
        "acceleration": "3.7 s (0-100 km/h)",
        "topSpeed": "250 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "200 kW DC",
        "seats": "5",
        "year": "2024+"
    }
]);
