registerCarModels([
    {
        "id": "id-buzz-gtx-2023",
        "brandId": "volkswagen",
        "name": "ID.Buzz",
        "trim": "GTX",
        "range": 450,
        "battery": 77,
        "weightKg": 2580,
        "dragCoefficient": 0.29,
        "img": "img/cars/volkswagen/Volkswagen-id.buzz.png",
        "power": "250 kW (340 HP)",
        "acceleration": "6.5 s (0-100 km/h)",
        "topSpeed": "160 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "185 kW DC",
        "seats": "5",
        "year": "2023+"
    },
    {
        "id": "id-buzz-lwb-gtx-2023",
        "brandId": "volkswagen",
        "name": "ID.Buzz",
        "trim": "LWB GTX",
        "range": 470,
        "battery": 86,
        "weightKg": 2700,
        "dragCoefficient": 0.3,
        "img": "img/cars/volkswagen/Volkswagen-id.buzz.png",
        "power": "250 kW (340 HP)",
        "acceleration": "6.6 s (0-100 km/h)",
        "topSpeed": "160 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "200 kW DC",
        "seats": "7",
        "year": "2023+"
    },
    {
        "id": "id-buzz-lwb-pro-2023",
        "brandId": "volkswagen",
        "name": "ID.Buzz",
        "trim": "LWB Pro",
        "range": 480,
        "battery": 77,
        "weightKg": 2590,
        "dragCoefficient": 0.3,
        "img": "img/cars/volkswagen/Volkswagen-id.buzz.png",
        "power": "210 kW (286 HP)",
        "acceleration": "7.8 s (0-100 km/h)",
        "topSpeed": "160 km/h",
        "batteryType": "Li-ion",
        "driveType": "RWD",
        "charging": "185 kW DC",
        "seats": "7",
        "year": "2023+"
    },
    {
        "id": "id-buzz-lwb-pro-s-2023",
        "brandId": "volkswagen",
        "name": "ID.Buzz",
        "trim": "LWB Pro S",
        "range": 500,
        "battery": 86,
        "weightKg": 2640,
        "dragCoefficient": 0.3,
        "img": "img/cars/volkswagen/Volkswagen-id.buzz.png",
        "power": "210 kW (286 HP)",
        "acceleration": "7.8 s (0-100 km/h)",
        "topSpeed": "160 km/h",
        "batteryType": "Li-ion",
        "driveType": "RWD",
        "charging": "200 kW DC",
        "seats": "7",
        "year": "2023+"
    },
    {
        "id": "id-buzz-pro-2023",
        "brandId": "volkswagen",
        "name": "ID.Buzz",
        "trim": "Pro",
        "range": 460,
        "battery": 77,
        "weightKg": 2470,
        "dragCoefficient": 0.29,
        "img": "img/cars/volkswagen/Volkswagen-id.buzz.png",
        "power": "210 kW (286 HP)",
        "acceleration": "7.9 s (0-100 km/h)",
        "topSpeed": "160 km/h",
        "batteryType": "Li-ion",
        "driveType": "RWD",
        "charging": "185 kW DC",
        "seats": "5",
        "year": "2023+"
    },
    {
        "id": "id-buzz-pure-2023",
        "brandId": "volkswagen",
        "name": "ID.Buzz",
        "trim": "Pure",
        "range": 360,
        "battery": 59,
        "weightKg": 2390,
        "dragCoefficient": 0.29,
        "img": "img/cars/volkswagen/Volkswagen-id.buzz.png",
        "power": "125 kW (170 HP)",
        "acceleration": "10.2 s (0-100 km/h)",
        "topSpeed": "145 km/h",
        "batteryType": "Li-ion",
        "driveType": "RWD",
        "charging": "165 kW DC",
        "seats": "5",
        "year": "2023+"
    }
]);
