registerCarModels([
    {
        "id": "model-3-long-range-awd-19-2019",
        "brandId": "tesla",
        "name": "Model 3",
        "trim": "Long Range AWD 19\"",
        "range": 530,
        "battery": 73.5,
        "weightKg": 1847,
        "dragCoefficient": 0.23,
        "img": "img/cars/tesla/Tesla_Model_3_early.png",
        "power": "258 kW (351 HP)",
        "acceleration": "4.8 s (0-100 km/h)",
        "topSpeed": "233 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "170 kW DC",
        "seats": "5",
        "year": "2018-2020"
    },
    {
        "id": "model-3-long-range-awd-aero-18-2019",
        "brandId": "tesla",
        "name": "Model 3",
        "trim": "Long Range AWD Aero 18\"",
        "range": 560,
        "battery": 73.5,
        "weightKg": 1847,
        "dragCoefficient": 0.23,
        "img": "img/cars/tesla/Tesla_Model_3_early.png",
        "power": "258 kW (351 HP)",
        "acceleration": "4.8 s (0-100 km/h)",
        "topSpeed": "233 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "170 kW DC",
        "seats": "5",
        "year": "2018-2020"
    },
    {
        "id": "model-3-long-range-performance-20-2019",
        "brandId": "tesla",
        "name": "Model 3",
        "trim": "Long Range Performance 20\"",
        "range": 507,
        "battery": 73.5,
        "weightKg": 1855,
        "dragCoefficient": 0.23,
        "img": "img/cars/tesla/Tesla_Model_3_early.png",
        "power": "340 kW (462 HP)",
        "acceleration": "3.4 s (0-100 km/h)",
        "topSpeed": "261 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "170 kW DC",
        "seats": "5",
        "year": "2018-2020"
    },
    {
        "id": "model-3-long-range-performance-minus-18-2019",
        "brandId": "tesla",
        "name": "Model 3",
        "trim": "Long Range Performance Minus 18\"",
        "range": 540,
        "battery": 73.5,
        "weightKg": 1848,
        "dragCoefficient": 0.23,
        "img": "img/cars/tesla/Tesla_Model_3_early.png",
        "power": "340 kW (462 HP)",
        "acceleration": "3.4 s (0-100 km/h)",
        "topSpeed": "261 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "170 kW DC",
        "seats": "5",
        "year": "2018-2020"
    },
    {
        "id": "model-3-long-range-performance-minus-19-2019",
        "brandId": "tesla",
        "name": "Model 3",
        "trim": "Long Range Performance Minus 19\"",
        "range": 525,
        "battery": 73.5,
        "weightKg": 1850,
        "dragCoefficient": 0.23,
        "img": "img/cars/tesla/Tesla_Model_3_early.png",
        "power": "340 kW (462 HP)",
        "acceleration": "3.4 s (0-100 km/h)",
        "topSpeed": "261 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "170 kW DC",
        "seats": "5",
        "year": "2018-2020"
    },
    {
        "id": "model-3-long-range-rwd-19-2019",
        "brandId": "tesla",
        "name": "Model 3",
        "trim": "Long Range RWD 19\"",
        "range": 575,
        "battery": 73.5,
        "weightKg": 1730,
        "dragCoefficient": 0.23,
        "img": "img/cars/tesla/Tesla_Model_3_early.png",
        "power": "239 kW (325 HP)",
        "acceleration": "5.3 s (0-100 km/h)",
        "topSpeed": "225 km/h",
        "batteryType": "Li-ion",
        "driveType": "RWD",
        "charging": "170 kW DC",
        "seats": "5",
        "year": "2018-2020"
    },
    {
        "id": "model-3-long-range-rwd-aero-18-2019",
        "brandId": "tesla",
        "name": "Model 3",
        "trim": "Long Range RWD Aero 18\"",
        "range": 602,
        "battery": 73.5,
        "weightKg": 1730,
        "dragCoefficient": 0.23,
        "img": "img/cars/tesla/Tesla_Model_3_early.png",
        "power": "239 kW (325 HP)",
        "acceleration": "5.3 s (0-100 km/h)",
        "topSpeed": "225 km/h",
        "batteryType": "Li-ion",
        "driveType": "RWD",
        "charging": "170 kW DC",
        "seats": "5",
        "year": "2018-2020"
    },
    {
        "id": "model-3-mid-range-rwd-19-2019",
        "brandId": "tesla",
        "name": "Model 3",
        "trim": "Mid Range RWD 19\"",
        "range": 420,
        "battery": 64,
        "weightKg": 1670,
        "dragCoefficient": 0.23,
        "img": "img/cars/tesla/Tesla_Model_3_early.png",
        "power": "190 kW (258 HP)",
        "acceleration": "5.6 s (0-100 km/h)",
        "topSpeed": "209 km/h",
        "batteryType": "Li-ion",
        "driveType": "RWD",
        "charging": "120 kW DC",
        "seats": "5",
        "year": "2018-2020"
    },
    {
        "id": "model-3-mid-range-rwd-aero-18-2019",
        "brandId": "tesla",
        "name": "Model 3",
        "trim": "Mid Range RWD Aero 18\"",
        "range": 450,
        "battery": 64,
        "weightKg": 1670,
        "dragCoefficient": 0.23,
        "img": "img/cars/tesla/Tesla_Model_3_early.png",
        "power": "190 kW (258 HP)",
        "acceleration": "5.6 s (0-100 km/h)",
        "topSpeed": "209 km/h",
        "batteryType": "Li-ion",
        "driveType": "RWD",
        "charging": "120 kW DC",
        "seats": "5",
        "year": "2018-2020"
    },
    {
        "id": "model-3-standard-range-plus-rwd-2019",
        "brandId": "tesla",
        "name": "Model 3",
        "trim": "Standard Range Plus RWD",
        "range": 409,
        "battery": 51,
        "weightKg": 1610,
        "dragCoefficient": 0.23,
        "img": "img/cars/tesla/Tesla_Model_3_early.png",
        "power": "190 kW (258 HP)",
        "acceleration": "5.6 s (0-100 km/h)",
        "topSpeed": "225 km/h",
        "batteryType": "Li-ion",
        "driveType": "RWD",
        "charging": "120 kW DC",
        "seats": "5",
        "year": "2018-2020"
    },
    {
        "id": "model-3-standard-range-rwd-2019",
        "brandId": "tesla",
        "name": "Model 3",
        "trim": "Standard Range RWD",
        "range": 354,
        "battery": 51,
        "weightKg": 1600,
        "dragCoefficient": 0.23,
        "img": "img/cars/tesla/Tesla_Model_3_early.png",
        "power": "180 kW (245 HP)",
        "acceleration": "5.8 s (0-100 km/h)",
        "topSpeed": "210 km/h",
        "batteryType": "Li-ion",
        "driveType": "RWD",
        "charging": "120 kW DC",
        "seats": "5",
        "year": "2018-2020"
    },
    {
        "id": "model-3-long-range-awd-2021",
        "brandId": "tesla",
        "name": "Model 3",
        "trim": "Long Range",
        "range": 614,
        "battery": 75,
        "weightKg": 1844,
        "dragCoefficient": 0.23,
        "img": "img/cars/tesla/Tesla_Model_3_early.png",
        "power": "340 kW (462 HP)",
        "acceleration": "4.4 s (0-100 km/h)",
        "topSpeed": "233 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "250 kW DC",
        "seats": "5",
        "year": "2021"
    },
    {
        "id": "model-3-long-range-82kwh-2021",
        "brandId": "tesla",
        "name": "Model 3",
        "trim": "Long Range 82 kWh",
        "range": 629,
        "battery": 80,
        "weightKg": 1850,
        "dragCoefficient": 0.23,
        "img": "img/cars/tesla/Tesla_Model_3_early.png",
        "power": "340 kW (462 HP)",
        "acceleration": "4.4 s (0-100 km/h)",
        "topSpeed": "233 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "250 kW DC",
        "seats": "5",
        "year": "2021"
    },
    {
        "id": "model-3-performance-awd-2021",
        "brandId": "tesla",
        "name": "Model 3",
        "trim": "Performance",
        "range": 567,
        "battery": 73.5,
        "weightKg": 1847,
        "dragCoefficient": 0.23,
        "img": "img/cars/tesla/Tesla_Model_3_early.png",
        "power": "377 kW (513 HP)",
        "acceleration": "3.3 s (0-100 km/h)",
        "topSpeed": "261 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "250 kW DC",
        "seats": "5",
        "year": "2021"
    },
    {
        "id": "model-3-standard-range-plus-2021",
        "brandId": "tesla",
        "name": "Model 3",
        "trim": "Standard Range Plus",
        "range": 448,
        "battery": 51,
        "weightKg": 1620,
        "dragCoefficient": 0.23,
        "img": "img/cars/tesla/Tesla_Model_3_early.png",
        "power": "208 kW (283 HP)",
        "acceleration": "5.8 s (0-100 km/h)",
        "topSpeed": "225 km/h",
        "batteryType": "Li-ion",
        "driveType": "RWD",
        "charging": "170 kW DC",
        "seats": "5",
        "year": "2021"
    },
    {
        "id": "model-3-standard-range-plus-lfp-2021",
        "brandId": "tesla",
        "name": "Model 3",
        "trim": "Standard Range Plus LFP",
        "range": 491,
        "battery": 57.5,
        "weightKg": 1630,
        "dragCoefficient": 0.23,
        "img": "img/cars/tesla/Tesla_Model_3_early.png",
        "power": "208 kW (283 HP)",
        "acceleration": "6.1 s (0-100 km/h)",
        "topSpeed": "225 km/h",
        "batteryType": "Li-ion LFP",
        "driveType": "RWD",
        "charging": "170 kW DC",
        "seats": "5",
        "year": "2021"
    },
    {
        "id": "model-3-long-range-awd-2022",
        "brandId": "tesla",
        "name": "Model 3",
        "trim": "Long Range",
        "range": 602,
        "battery": 79,
        "weightKg": 1848,
        "dragCoefficient": 0.23,
        "img": "img/cars/tesla/Tesla_Model_3_early.png",
        "power": "366 kW (498 HP)",
        "acceleration": "4.4 s (0-100 km/h)",
        "topSpeed": "233 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "250 kW DC",
        "seats": "5",
        "year": "2022-2023"
    },
    {
        "id": "model-3-performance-awd-2022",
        "brandId": "tesla",
        "name": "Model 3",
        "trim": "Performance",
        "range": 547,
        "battery": 79,
        "weightKg": 1855,
        "dragCoefficient": 0.23,
        "img": "img/cars/tesla/Tesla_Model_3_early.png",
        "power": "377 kW (513 HP)",
        "acceleration": "3.3 s (0-100 km/h)",
        "topSpeed": "261 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "250 kW DC",
        "seats": "5",
        "year": "2022-2023"
    },
    {
        "id": "model-3-standard-60kwh-2022",
        "brandId": "tesla",
        "name": "Model 3",
        "trim": "Standard 60 kWh",
        "range": 513,
        "battery": 57.5,
        "weightKg": 1660,
        "dragCoefficient": 0.23,
        "img": "img/cars/tesla/Tesla_Model_3_early.png",
        "power": "208 kW (283 HP)",
        "acceleration": "6.1 s (0-100 km/h)",
        "topSpeed": "225 km/h",
        "batteryType": "Li-ion LFP",
        "driveType": "RWD",
        "charging": "170 kW DC",
        "seats": "5",
        "year": "2022-2023"
    },
    {
        "id": "model-3-standard-range-rwd-2024-2026",
        "brandId": "tesla",
        "name": "Model 3",
        "trim": "Standard Range RWD",
        "range": 554,
        "battery": 57.5,
        "weightKg": 1765,
        "dragCoefficient": 0.22,
        "img": "img/cars/tesla/Tesla_Model_3.png",
        "power": "208 kW (283 HP)",
        "acceleration": "6.1 s (0-100 km/h)",
        "topSpeed": "201 km/h",
        "batteryType": "Li-ion LFP",
        "driveType": "RWD",
        "charging": "170 kW DC",
        "seats": "5",
        "year": "2024-2026"
    },
    {
        "id": "model-3-long-range-awd-2024",
        "brandId": "tesla",
        "name": "Model 3",
        "trim": "Long Range AWD",
        "range": 629,
        "battery": 79,
        "weightKg": 1828,
        "dragCoefficient": 0.22,
        "img": "img/cars/tesla/Tesla_Model_3.png",
        "power": "366 kW (498 HP)",
        "acceleration": "4.4 s (0-100 km/h)",
        "topSpeed": "201 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "250 kW DC",
        "seats": "5",
        "year": "2024+"
    },
    {
        "id": "model-3-long-range-rwd-2024",
        "brandId": "tesla",
        "name": "Model 3",
        "trim": "Long Range RWD",
        "range": 702,
        "battery": 79,
        "weightKg": 1775,
        "dragCoefficient": 0.22,
        "img": "img/cars/tesla/Tesla_Model_3.png",
        "power": "230 kW (313 HP)",
        "acceleration": "5.2 s (0-100 km/h)",
        "topSpeed": "201 km/h",
        "batteryType": "Li-ion",
        "driveType": "RWD",
        "charging": "250 kW DC",
        "seats": "5",
        "year": "2024+"
    },
    {
        "id": "model-3-performance-awd-2024",
        "brandId": "tesla",
        "name": "Model 3",
        "trim": "Performance AWD",
        "range": 560,
        "battery": 79,
        "weightKg": 1850,
        "dragCoefficient": 0.22,
        "img": "img/cars/tesla/Tesla_Model_3.png",
        "power": "377 kW (513 HP)",
        "acceleration": "3.1 s (0-100 km/h)",
        "topSpeed": "262 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "250 kW DC",
        "seats": "5",
        "year": "2024+",
        "isEstimate": true
    },
    {
        "id": "model-3-standard-range-rwd-2026",
        "brandId": "tesla",
        "name": "Model 3",
        "trim": "Standard Range RWD",
        "range": 580,
        "battery": 60,
        "weightKg": 1770,
        "dragCoefficient": 0.22,
        "img": "img/cars/tesla/Tesla_Model_3.png",
        "power": "220 kW (299 HP)",
        "acceleration": "5.9 s (0-100 km/h)",
        "topSpeed": "205 km/h",
        "batteryType": "Li-ion LFP",
        "driveType": "RWD",
        "charging": "200 kW DC",
        "seats": "5",
        "year": "2026+",
        "isEstimate": true
    }
]);
