registerCarModels([
    {
        "id": "rz-350e-2026",
        "brandId": "lexus",
        "name": "RZ",
        "trim": "350e",
        "range": 350,
        "battery": 77,
        "weightKg": 2080,
        "dragCoefficient": 0.28,
        "img": "img/cars/lexus/Lexus_rz_2026.png",
        "power": "150 kW (204 HP)",
        "acceleration": "8.2 s (0-100 km/h)",
        "topSpeed": "170 km/h",
        "batteryType": "Li-ion",
        "driveType": "RWD",
        "charging": "150 kW DC",
        "seats": "5",
        "year": "2026+"
    },
    {
        "id": "rz-500e-2026",
        "brandId": "lexus",
        "name": "RZ",
        "trim": "500e",
        "range": 430,
        "battery": 77,
        "weightKg": 2150,
        "dragCoefficient": 0.28,
        "img": "img/cars/lexus/Lexus_rz_2026.png",
        "power": "230 kW (313 HP)",
        "acceleration": "5.6 s (0-100 km/h)",
        "topSpeed": "180 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "150 kW DC",
        "seats": "5",
        "year": "2026+"
    },
    {
        "id": "rz-550e-f-sport-2026",
        "brandId": "lexus",
        "name": "RZ",
        "trim": "550e F SPORT",
        "range": 410,
        "battery": 77,
        "weightKg": 2180,
        "dragCoefficient": 0.28,
        "img": "img/cars/lexus/Lexus_rz_2026.png",
        "power": "270 kW (367 HP)",
        "acceleration": "4.8 s (0-100 km/h)",
        "topSpeed": "190 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "150 kW DC",
        "seats": "5",
        "year": "2026+"
    },
    {
        "id": "rz-600e-f-sport-2026",
        "brandId": "lexus",
        "name": "RZ",
        "trim": "600e F SPORT",
        "range": 390,
        "battery": 77,
        "weightKg": 2210,
        "dragCoefficient": 0.28,
        "img": "img/cars/lexus/Lexus_rz_2026.png",
        "power": "310 kW (421 HP)",
        "acceleration": "4.2 s (0-100 km/h)",
        "topSpeed": "200 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "150 kW DC",
        "seats": "5",
        "year": "2026+"
    },
    {
        "id": "rz-300e-2024",
        "brandId": "lexus",
        "name": "RZ",
        "trim": "300e",
        "range": 315,
        "battery": 64,
        "weightKg": 2000,
        "dragCoefficient": 0.28,
        "img": "img/cars/lexus/Lexus_rz.png",
        "power": "130 kW (177 HP)",
        "acceleration": "9.0 s (0-100 km/h)",
        "topSpeed": "160 km/h",
        "batteryType": "Li-ion",
        "driveType": "FWD",
        "charging": "100 kW DC",
        "seats": "5",
        "year": "2024-2025"
    },
    {
        "id": "rz-450e-2023",
        "brandId": "lexus",
        "name": "RZ",
        "trim": "450e",
        "range": 395,
        "battery": 64,
        "weightKg": 2105,
        "dragCoefficient": 0.28,
        "img": "img/cars/lexus/Lexus_rz.png",
        "power": "230 kW (313 HP)",
        "acceleration": "5.6 s (0-100 km/h)",
        "topSpeed": "180 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "150 kW DC",
        "seats": "5",
        "year": "2023-2025"
    }
]);
