registerCarModels([
    {
        "id": "i5-edrive40-sedan-2024",
        "brandId": "bmw",
        "name": "i5",
        "trim": "Sedan eDrive40",
        "range": 582,
        "battery": 81.2,
        "weightKg": 2205,
        "dragCoefficient": 0.24,
        "img": "img/cars/bmw/BMW_i5.png",
        "power": "250 kW (340 HP)",
        "acceleration": "5.7 s (0-100 km/h)",
        "topSpeed": "193 km/h",
        "batteryType": "Li-ion",
        "driveType": "RWD",
        "charging": "205 kW DC",
        "seats": "5",
        "year": "2024+"
    },
    {
        "id": "i5-m60-sedan-2024",
        "brandId": "bmw",
        "name": "i5",
        "trim": "Sedan M60 xDrive",
        "range": 516,
        "battery": 81.2,
        "weightKg": 2380,
        "dragCoefficient": 0.25,
        "img": "img/cars/bmw/BMW_i5.png",
        "power": "442 kW (601 HP)",
        "acceleration": "3.8 s (0-100 km/h)",
        "topSpeed": "230 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "205 kW DC",
        "seats": "5",
        "year": "2024+"
    },
    {
        "id": "i5-edrive40-touring-2025",
        "brandId": "bmw",
        "name": "i5",
        "trim": "Touring eDrive40",
        "range": 560,
        "battery": 81.2,
        "weightKg": 2255,
        "dragCoefficient": 0.23,
        "img": "img/cars/bmw/BMW_i5_touring.png",
        "power": "250 kW (340 HP)",
        "acceleration": "5.7 s (0-100 km/h)",
        "topSpeed": "193 km/h",
        "batteryType": "Li-ion",
        "driveType": "RWD",
        "charging": "205 kW DC",
        "seats": "5",
        "year": "2025+"
    },
    {
        "id": "i5-m60-touring-2025",
        "brandId": "bmw",
        "name": "i5",
        "trim": "Touring M60 xDrive",
        "range": 506,
        "battery": 81.2,
        "weightKg": 2425,
        "dragCoefficient": 0.23,
        "img": "img/cars/bmw/BMW_i5_touring.png",
        "power": "442 kW (601 HP)",
        "acceleration": "3.8 s (0-100 km/h)",
        "topSpeed": "230 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "205 kW DC",
        "seats": "5",
        "year": "2025+"
    }
]);
