registerCarModels([
    {
        "id": "zeekr-7x-long-range-2025",
        "brandId": "zeekr",
        "name": "7X",
        "trim": "Long Range",
        "range": 670,
        "battery": 94,
        "weightKg": 2480,
        "dragCoefficient": 0.28,
        "img": "img/cars/zeekr/Zeekr_7x.png",
        "power": "230 kW (313 HP)",
        "acceleration": "5.8 s (0-100 km/h)",
        "topSpeed": "210 km/h",
        "batteryType": "Li-ion LFP",
        "driveType": "Dual Motor AWD",
        "charging": "200 kW DC",
        "seats": "7",
        "year": "2025+"
    },
    {
        "id": "zeekr-7x-performance-2025",
        "brandId": "zeekr",
        "name": "7X",
        "trim": "Performance",
        "range": 650,
        "battery": 94,
        "weightKg": 2500,
        "dragCoefficient": 0.28,
        "img": "img/cars/zeekr/Zeekr_7x.png",
        "power": "280 kW (380 HP)",
        "acceleration": "5.3 s (0-100 km/h)",
        "topSpeed": "220 km/h",
        "batteryType": "Li-ion LFP",
        "driveType": "Dual Motor AWD",
        "charging": "200 kW DC",
        "seats": "7",
        "year": "2025+"
    },
    {
        "id": "zeekr-7x-premium-rwd-2025",
        "brandId": "zeekr",
        "name": "7X",
        "trim": "Premium RWD",
        "range": 480,
        "battery": 71,
        "weightKg": 2380,
        "dragCoefficient": 0.28,
        "img": "img/cars/zeekr/Zeekr_7x.png",
        "power": "160 kW (218 HP)",
        "acceleration": "7.2 s (0-100 km/h)",
        "topSpeed": "190 km/h",
        "batteryType": "Li-ion LFP",
        "driveType": "RWD",
        "charging": "150 kW DC",
        "seats": "7",
        "year": "2025+"
    }
]);
