registerCarModels([
    {
        "id": "id-5-pro-2024",
        "brandId": "volkswagen",
        "name": "ID.5",
        "trim": "Pro",
        "range": 560,
        "battery": 77,
        "weightKg": 2140,
        "dragCoefficient": 0.26,
        "img": "img/cars/volkswagen/Volkswagen_ID.5.png",
        "power": "210 kW (286 HP)",
        "acceleration": "6.5 s (0-100 km/h)",
        "topSpeed": "180 km/h",
        "batteryType": "Li-ion",
        "driveType": "RWD",
        "charging": "175 kW DC",
        "seats": "5",
        "year": "2024+"
    },
    {
        "id": "id-5-pro-gtx-2024",
        "brandId": "volkswagen",
        "name": "ID.5",
        "trim": "Pro GTX",
        "range": 520,
        "battery": 77,
        "weightKg": 2240,
        "dragCoefficient": 0.26,
        "img": "img/cars/volkswagen/Volkswagen_ID.5.png",
        "power": "250 kW (340 HP)",
        "acceleration": "5.4 s (0-100 km/h)",
        "topSpeed": "180 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "175 kW DC",
        "seats": "5",
        "year": "2024+"
    },
    {
        "id": "id-5-pure-52-2024",
        "brandId": "volkswagen",
        "name": "ID.5",
        "trim": "Pure",
        "range": 380,
        "battery": 52,
        "weightKg": 2030,
        "dragCoefficient": 0.26,
        "img": "img/cars/volkswagen/Volkswagen_ID.5.png",
        "power": "125 kW (170 HP)",
        "acceleration": "8.9 s (0-100 km/h)",
        "topSpeed": "160 km/h",
        "batteryType": "Li-ion",
        "driveType": "RWD",
        "charging": "145 kW DC",
        "seats": "5",
        "year": "2024+"
    },
    {
        "id": "id-5-77-rwd-2022",
        "brandId": "volkswagen",
        "name": "ID.5",
        "trim": "77 kWh",
        "range": 545,
        "battery": 77,
        "weightKg": 2120,
        "dragCoefficient": 0.26,
        "img": "img/cars/volkswagen/Volkswagen_ID.5.png",
        "power": "150 kW (204 HP)",
        "acceleration": "8.4 s (0-100 km/h)",
        "topSpeed": "160 km/h",
        "batteryType": "Li-ion",
        "driveType": "RWD",
        "charging": "135 kW DC",
        "seats": "5",
        "year": "2022+"
    },
    {
        "id": "id-5-gtx-77-2022",
        "brandId": "volkswagen",
        "name": "ID.5",
        "trim": "GTX 77 kWh",
        "range": 510,
        "battery": 77,
        "weightKg": 2230,
        "dragCoefficient": 0.26,
        "img": "img/cars/volkswagen/Volkswagen_ID.5.png",
        "power": "220 kW (299 HP)",
        "acceleration": "6.3 s (0-100 km/h)",
        "topSpeed": "180 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "135 kW DC",
        "seats": "5",
        "year": "2022+"
    }
]);
