registerCarModels([
    {
        "id": "zeekr-001-long-range-rwd-2024",
        "brandId": "zeekr",
        "name": "001",
        "trim": "Long Range RWD",
        "range": 620,
        "battery": 100,
        "weightKg": 2150,
        "dragCoefficient": 0.27,
        "img": "img/cars/zeekr/Zeekr_001.png",
        "power": "150 kW (204 HP)",
        "acceleration": "7.5 s (0-100 km/h)",
        "topSpeed": "190 km/h",
        "batteryType": "Li-ion LFP",
        "driveType": "RWD",
        "charging": "200 kW DC",
        "seats": "5",
        "year": "2024+"
    },
    {
        "id": "zeekr-001-performance-awd-2024",
        "brandId": "zeekr",
        "name": "001",
        "trim": "Performance AWD",
        "range": 580,
        "battery": 100,
        "weightKg": 2180,
        "dragCoefficient": 0.27,
        "img": "img/cars/zeekr/Zeekr_001.png",
        "power": "290 kW (394 HP)",
        "acceleration": "5.0 s (0-100 km/h)",
        "topSpeed": "210 km/h",
        "batteryType": "Li-ion LFP",
        "driveType": "Dual Motor AWD",
        "charging": "200 kW DC",
        "seats": "5",
        "year": "2024+"
    },
    {
        "id": "zeekr-001-privilege-awd-2024",
        "brandId": "zeekr",
        "name": "001",
        "trim": "Privilege AWD",
        "range": 580,
        "battery": 100,
        "weightKg": 2200,
        "dragCoefficient": 0.27,
        "img": "img/cars/zeekr/Zeekr_001.png",
        "power": "290 kW (394 HP)",
        "acceleration": "5.0 s (0-100 km/h)",
        "topSpeed": "210 km/h",
        "batteryType": "Li-ion LFP",
        "driveType": "Dual Motor AWD",
        "charging": "200 kW DC",
        "seats": "5",
        "year": "2024+"
    }
]);
