registerCarModels([
    {
        "id": "zdx-a-spec-awd-2025",
        "brandId": "acura",
        "name": "ZDX",
        "trim": "A-Spec",
        "range": 520,
        "battery": 102,
        "weightKg": 2250,
        "dragCoefficient": 0.29,
        "img": "img/cars/acura/Acura_zdx.png",
        "power": "320 kW (429 HP)",
        "acceleration": "4.5 s (0-100 km/h)",
        "topSpeed": "210 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "200 kW DC",
        "seats": "5",
        "year": "2025+"
    },
    {
        "id": "zdx-a-spec-rwd-2025",
        "brandId": "acura",
        "name": "ZDX",
        "trim": "A-Spec",
        "range": 560,
        "battery": 102,
        "weightKg": 2150,
        "dragCoefficient": 0.29,
        "img": "img/cars/acura/Acura_zdx.png",
        "power": "280 kW (375 HP)",
        "acceleration": "5.1 s (0-100 km/h)",
        "topSpeed": "200 km/h",
        "batteryType": "Li-ion",
        "driveType": "RWD",
        "charging": "200 kW DC",
        "seats": "5",
        "year": "2025+"
    },
    {
        "id": "zdx-type-s-2025",
        "brandId": "acura",
        "name": "ZDX",
        "trim": "Type S",
        "range": 500,
        "battery": 102,
        "weightKg": 2300,
        "dragCoefficient": 0.29,
        "img": "img/cars/acura/Acura_zdx.png",
        "power": "400 kW (536 HP)",
        "acceleration": "3.8 s (0-100 km/h)",
        "topSpeed": "240 km/h",
        "batteryType": "Li-ion",
        "driveType": "Dual Motor AWD",
        "charging": "200 kW DC",
        "seats": "5",
        "year": "2025+"
    }
]);
