registerCarModels([
    {
        "id": "r2-2025",
        "brandId": "rivian",
        "name": "R2",
        "trim": "Standard",
        "range": 320,
        "battery": 75,
        "weightKg": 1800,
        "dragCoefficient": 0.30,
        "img": "img/cars/rivian/Rivian_R2.png",
        "power": "150 kW",
        "acceleration": "7.5 s (0-100 km/h)",
        "topSpeed": "170 km/h",
        "batteryType": "Li-ion",
        "driveType": "RWD",
        "charging": "150 kW DC",
        "seats": "5",
        "year": "2025+"
    },
    {
        "id": "r2-2026-performance",
        "brandId": "rivian",
        "name": "R2",
        "trim": "Performance",
        "range": 360,
        "battery": 87.9,
        "weightKg": 1850,
        "dragCoefficient": 0.30,
        "img": "img/cars/rivian/Rivian_R2.png",
        "power": "Dual Motor 220 kW",
        "acceleration": "5.2 s (0-100 km/h)",
        "topSpeed": "200 km/h",
        "batteryType": "Li-ion",
        "driveType": "AWD",
        "charging": "200 kW DC",
        "seats": "5",
        "year": "2026+"
    },
    {
        "id": "r2-2026-premium",
        "brandId": "rivian",
        "name": "R2",
        "trim": "Premium",
        "range": 360,
        "battery": 87.9,
        "weightKg": 1860,
        "dragCoefficient": 0.30,
        "img": "img/cars/rivian/Rivian_R2.png",
        "power": "Dual Motor 220 kW",
        "acceleration": "5.4 s (0-100 km/h)",
        "topSpeed": "200 km/h",
        "batteryType": "Li-ion",
        "driveType": "AWD",
        "charging": "200 kW DC",
        "seats": "5",
        "year": "2026+"
    },
    {
        "id": "r2-2027-standard",
        "brandId": "rivian",
        "name": "R2",
        "trim": "Standard",
        "range": 260,
        "battery": 65,
        "weightKg": 1750,
        "dragCoefficient": 0.30,
        "img": "img/cars/rivian/Rivian_R2.png",
        "power": "140 kW",
        "acceleration": "8.0 s (0-100 km/h)",
        "topSpeed": "170 km/h",
        "batteryType": "Li-ion",
        "driveType": "RWD",
        "charging": "150 kW DC",
        "seats": "5",
        "year": "2027+"
    },
    {
        "id": "r2-2027-standard-lr",
        "brandId": "rivian",
        "name": "R2",
        "trim": "Standard Long Range",
        "range": 320,
        "battery": 87.9,
        "weightKg": 1780,
        "dragCoefficient": 0.30,
        "img": "img/cars/rivian/Rivian_R2.png",
        "power": "140 kW",
        "acceleration": "7.2 s (0-100 km/h)",
        "topSpeed": "180 km/h",
        "batteryType": "Li-ion",
        "driveType": "RWD",
        "charging": "200 kW DC",
        "seats": "5",
        "year": "2027+"
    }
]);
